package com.cinematch.battle;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.NOT_FOUND;

@Service
public class MovieBattleService {

    private final JdbcTemplate jdbcTemplate;

    public MovieBattleService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    public void initTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS movie_battle (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    creator_user_id BIGINT,
                    movie_a_id BIGINT NOT NULL,
                    movie_b_id BIGINT,
                    battle_type VARCHAR(20) NOT NULL DEFAULT 'USER',
                    battle_label VARCHAR(200),
                    option_a_label VARCHAR(100),
                    option_b_label VARCHAR(100),
                    option_a_image_url VARCHAR(500),
                    option_b_image_url VARCHAR(500),
                    vote_a INT NOT NULL DEFAULT 0,
                    vote_b INT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_battle_creator FOREIGN KEY (creator_user_id) REFERENCES "USER"(id),
                    CONSTRAINT fk_battle_a FOREIGN KEY (movie_a_id) REFERENCES movie(id),
                    CONSTRAINT fk_battle_b FOREIGN KEY (movie_b_id) REFERENCES movie(id)
                )
                """);
        addColumnIfMissing("movie_battle", "creator_user_id", "BIGINT");
        addColumnIfMissing("movie_battle", "battle_label", "VARCHAR(200)");
        addColumnIfMissing("movie_battle", "battle_type", "VARCHAR(20) NOT NULL DEFAULT 'USER'");
        addColumnIfMissing("movie_battle", "option_a_label", "VARCHAR(100)");
        addColumnIfMissing("movie_battle", "option_b_label", "VARCHAR(100)");
        addColumnIfMissing("movie_battle", "option_a_image_url", "VARCHAR(500)");
        addColumnIfMissing("movie_battle", "option_b_image_url", "VARCHAR(500)");
        allowNullableMovieB();

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS battle_vote (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    battle_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    voted_movie_id BIGINT,
                    voted_option VARCHAR(1),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bvote_battle FOREIGN KEY (battle_id) REFERENCES movie_battle(id),
                    CONSTRAINT fk_bvote_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
                    CONSTRAINT fk_bvote_movie FOREIGN KEY (voted_movie_id) REFERENCES movie(id),
                    CONSTRAINT uq_battle_user UNIQUE (battle_id, user_id)
                )
                """);
        addColumnIfMissing("battle_vote", "voted_option", "VARCHAR(1)");
        allowNullableVotedMovie();

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS battle_comment (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    battle_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    content VARCHAR(1000) NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bcomment_battle FOREIGN KEY (battle_id) REFERENCES movie_battle(id),
                    CONSTRAINT fk_bcomment_user FOREIGN KEY (user_id) REFERENCES "USER"(id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS idx_battle_comment_battle_created
                ON battle_comment (battle_id, created_at)
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS battle_comment_like (
                    comment_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    PRIMARY KEY (comment_id, user_id),
                    CONSTRAINT fk_bcomment_like_comment FOREIGN KEY (comment_id) REFERENCES battle_comment(id),
                    CONSTRAINT fk_bcomment_like_user FOREIGN KEY (user_id) REFERENCES "USER"(id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS battle_share (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    battle_id BIGINT NOT NULL,
                    sender_user_id BIGINT NOT NULL,
                    receiver_user_id BIGINT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bshare_battle FOREIGN KEY (battle_id) REFERENCES movie_battle(id),
                    CONSTRAINT fk_bshare_sender FOREIGN KEY (sender_user_id) REFERENCES "USER"(id),
                    CONSTRAINT fk_bshare_receiver FOREIGN KEY (receiver_user_id) REFERENCES "USER"(id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE INDEX IF NOT EXISTS idx_battle_share_receiver
                ON battle_share (receiver_user_id, created_at)
                """);
    }

    public List<Map<String, Object>> getActiveBattles(Long currentUserId) {
        initTables();
        List<Map<String, Object>> battles = jdbcTemplate.query("""
                SELECT b.id, b.creator_user_id, b.battle_type, b.battle_label,
                       b.option_a_label, b.option_b_label, b.option_a_image_url, b.option_b_image_url,
                       b.vote_a, b.vote_b, b.created_at,
                       u.login_id AS creator_login_id,
                       u.nickname AS creator_nickname,
                       ma.id AS movie_a_id, ma.movie_cd AS movie_a_code,
                       COALESCE(ma.title, ma.movie_name) AS movie_a_title,
                       ma.poster_image_url AS movie_a_poster,
                       COALESCE(ma.vote_average, 0) AS movie_a_rating,
                       mb.id AS movie_b_id, mb.movie_cd AS movie_b_code,
                       COALESCE(mb.title, mb.movie_name) AS movie_b_title,
                       mb.poster_image_url AS movie_b_poster,
                       COALESCE(mb.vote_average, 0) AS movie_b_rating,
                       bv.voted_option AS my_vote
                FROM movie_battle b
                JOIN movie ma ON ma.id = b.movie_a_id
                LEFT JOIN movie mb ON mb.id = b.movie_b_id
                LEFT JOIN "USER" u ON u.id = b.creator_user_id
                LEFT JOIN battle_vote bv ON bv.battle_id = b.id AND bv.user_id = ?
                ORDER BY b.created_at DESC
                LIMIT 20
                """, (rs, rowNum) -> toBattleRow(rs), currentUserId == null ? -1L : currentUserId);
        for (Map<String, Object> battle : battles) {
            Object id = battle.get("id");
            if (id instanceof Number n) {
                Map<String, Object> topComment = fetchTopComment(n.longValue());
                battle.put("topComment", topComment);
                battle.put("hasTopComment", !topComment.isEmpty());
            }
        }
        return battles;
    }

    public Map<String, Object> getBattle(Long battleId, Long currentUserId) {
        initTables();
        Map<String, Object> battle = jdbcTemplate.query("""
                SELECT b.id, b.creator_user_id, b.battle_type, b.battle_label,
                       b.option_a_label, b.option_b_label, b.option_a_image_url, b.option_b_image_url,
                       b.vote_a, b.vote_b, b.created_at,
                       u.login_id AS creator_login_id,
                       u.nickname AS creator_nickname,
                       ma.id AS movie_a_id, ma.movie_cd AS movie_a_code,
                       COALESCE(ma.title, ma.movie_name) AS movie_a_title,
                       ma.poster_image_url AS movie_a_poster,
                       COALESCE(ma.vote_average, 0) AS movie_a_rating,
                       mb.id AS movie_b_id, mb.movie_cd AS movie_b_code,
                       COALESCE(mb.title, mb.movie_name) AS movie_b_title,
                       mb.poster_image_url AS movie_b_poster,
                       COALESCE(mb.vote_average, 0) AS movie_b_rating,
                       bv.voted_option AS my_vote
                FROM movie_battle b
                JOIN movie ma ON ma.id = b.movie_a_id
                LEFT JOIN movie mb ON mb.id = b.movie_b_id
                LEFT JOIN "USER" u ON u.id = b.creator_user_id
                LEFT JOIN battle_vote bv ON bv.battle_id = b.id AND bv.user_id = ?
                WHERE b.id = ?
                """, rs -> rs.next() ? toBattleRow(rs) : null, currentUserId == null ? -1L : currentUserId, battleId);
        if (battle == null) {
            throw new ResponseStatusException(NOT_FOUND, "배틀을 찾을 수 없습니다.");
        }
        battle.put("commentCount", countComments(battleId));
        return battle;
    }

    public Map<String, Object> createBattle(String title,
                                            Long movieAId,
                                            Long movieBId,
                                            String optionALabel,
                                            String optionBLabel,
                                            String optionAImageUrl,
                                            String optionBImageUrl,
                                            Long creatorUserId) {
        initTables();
        String normalizedTitle = requireText(title, "배틀 타이틀을 입력해주세요.", 200);
        String normalizedOptionA = requireText(optionALabel, "첫 번째 선택지 이름을 입력해주세요.", 100);
        String normalizedOptionB = requireText(optionBLabel, "두 번째 선택지 이름을 입력해주세요.", 100);
        String normalizedImageA = requireText(optionAImageUrl, "첫 번째 선택지 이미지를 입력해주세요.", 500);
        String normalizedImageB = requireText(optionBImageUrl, "두 번째 선택지 이미지를 입력해주세요.", 500);

        if (movieAId == null) {
            throw new ResponseStatusException(BAD_REQUEST, "영화를 하나 이상 선택해주세요.");
        }
        if (movieBId != null && movieAId.equals(movieBId)) {
            throw new ResponseStatusException(BAD_REQUEST, "서로 다른 영화를 선택해주세요.");
        }
        requireMovie(movieAId);
        if (movieBId != null) {
            requireMovie(movieBId);
        }

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement("""
                    INSERT INTO movie_battle (
                        creator_user_id, movie_a_id, movie_b_id, battle_type, battle_label,
                        option_a_label, option_b_label, option_a_image_url, option_b_image_url
                    )
                    VALUES (?, ?, ?, 'USER', ?, ?, ?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS);
            ps.setLong(1, creatorUserId);
            ps.setLong(2, movieAId);
            if (movieBId == null) {
                ps.setObject(3, null);
            } else {
                ps.setLong(3, movieBId);
            }
            ps.setString(4, normalizedTitle);
            ps.setString(5, normalizedOptionA);
            ps.setString(6, normalizedOptionB);
            ps.setString(7, normalizedImageA);
            ps.setString(8, normalizedImageB);
            return ps;
        }, keyHolder);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("id", keyHolder.getKey() == null ? null : keyHolder.getKey().longValue());
        result.put("created", true);
        return result;
    }

    public Map<String, Object> vote(Long battleId, String option, Long userId) {
        initTables();
        String normalizedOption = option == null ? "" : option.trim().toUpperCase();
        if (!normalizedOption.equals("A") && !normalizedOption.equals("B")) {
            throw new ResponseStatusException(BAD_REQUEST, "선택지는 A 또는 B여야 합니다.");
        }

        Integer exists = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM movie_battle WHERE id = ?", Integer.class, battleId);
        if (exists == null || exists == 0) {
            throw new ResponseStatusException(NOT_FOUND, "배틀을 찾을 수 없습니다.");
        }

        String prevVote = jdbcTemplate.query(
                "SELECT voted_option FROM battle_vote WHERE battle_id = ? AND user_id = ?",
                rs -> rs.next() ? rs.getString("voted_option") : null,
                battleId, userId);

        if (prevVote != null) {
            jdbcTemplate.update("DELETE FROM battle_vote WHERE battle_id = ? AND user_id = ?", battleId, userId);
            decrementVote(battleId, prevVote);
            if (prevVote.equals(normalizedOption)) {
                return fetchResult(battleId, null);
            }
        }

        jdbcTemplate.update(
                "INSERT INTO battle_vote (battle_id, user_id, voted_option) VALUES (?, ?, ?)",
                battleId, userId, normalizedOption);
        incrementVote(battleId, normalizedOption);
        return fetchResult(battleId, normalizedOption);
    }

    public List<Map<String, Object>> listComments(Long battleId, Long currentUserId) {
        initTables();
        requireBattle(battleId);
        return jdbcTemplate.query("""
                SELECT bc.id AS comment_id, bc.content, bc.created_at,
                       u.id AS user_id, u.login_id, u.nickname, u.profile_image_url,
                       (SELECT COUNT(*) FROM battle_comment_like bcl WHERE bcl.comment_id = bc.id) AS like_count,
                       CASE WHEN EXISTS (
                           SELECT 1 FROM battle_comment_like bcl
                           WHERE bcl.comment_id = bc.id AND bcl.user_id = ?
                       ) THEN TRUE ELSE FALSE END AS liked_by_me
                FROM battle_comment bc
                JOIN "USER" u ON u.id = bc.user_id
                WHERE bc.battle_id = ?
                ORDER BY bc.created_at ASC
                """, (rs, rowNum) -> mapCommentRow(
                rs.getLong("comment_id"),
                rs.getString("content"),
                rs.getTimestamp("created_at"),
                rs.getLong("user_id"),
                rs.getString("login_id"),
                rs.getString("nickname"),
                rs.getString("profile_image_url"),
                rs.getInt("like_count"),
                rs.getBoolean("liked_by_me"),
                currentUserId), currentUserId == null ? -1L : currentUserId, battleId);
    }

    public Map<String, Object> addComment(Long battleId, Long userId, String content) {
        initTables();
        requireBattle(battleId);
        String normalizedContent = requireText(content, "댓글 내용을 입력해주세요.", 1000);
        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement ps = connection.prepareStatement("""
                    INSERT INTO battle_comment (battle_id, user_id, content)
                    VALUES (?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS);
            ps.setLong(1, battleId);
            ps.setLong(2, userId);
            ps.setString(3, normalizedContent);
            return ps;
        }, keyHolder);

        Long commentId = keyHolder.getKey() == null ? null : keyHolder.getKey().longValue();
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("comment", fetchComment(commentId, userId));
        result.put("commentCount", countComments(battleId));
        return result;
    }

    public Map<String, Object> toggleCommentLike(Long commentId, Long userId) {
        initTables();
        Long battleId = jdbcTemplate.query("""
                SELECT battle_id
                FROM battle_comment
                WHERE id = ?
                """, rs -> rs.next() ? rs.getLong("battle_id") : null, commentId);
        if (battleId == null) {
            throw new ResponseStatusException(NOT_FOUND, "댓글을 찾을 수 없습니다.");
        }

        Integer liked = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM battle_comment_like
                WHERE comment_id = ? AND user_id = ?
                """, Integer.class, commentId, userId);
        boolean nowLiked;
        if (liked != null && liked > 0) {
            jdbcTemplate.update("DELETE FROM battle_comment_like WHERE comment_id = ? AND user_id = ?", commentId, userId);
            nowLiked = false;
        } else {
            jdbcTemplate.update("INSERT INTO battle_comment_like (comment_id, user_id) VALUES (?, ?)", commentId, userId);
            nowLiked = true;
        }

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("liked", nowLiked);
        result.put("likeCount", countCommentLikes(commentId));
        result.put("topComment", fetchTopComment(battleId));
        return result;
    }

    public List<Map<String, Object>> listMutualFollowers(Long currentUserId) {
        initTables();
        return jdbcTemplate.query("""
                SELECT u.id, u.login_id, u.nickname, u.profile_image_url
                FROM user_follow outgoing
                JOIN user_follow incoming
                  ON incoming.follower_user_id = outgoing.following_user_id
                 AND incoming.following_user_id = outgoing.follower_user_id
                JOIN "USER" u ON u.id = outgoing.following_user_id
                WHERE outgoing.follower_user_id = ?
                ORDER BY COALESCE(u.nickname, u.login_id), u.login_id
                """, (rs, rowNum) -> {
            Map<String, Object> user = new LinkedHashMap<>();
            user.put("userId", rs.getLong("id"));
            user.put("loginId", rs.getString("login_id"));
            user.put("nickname", rs.getString("nickname"));
            user.put("profileImageUrl", rs.getString("profile_image_url"));
            return user;
        }, currentUserId);
    }

    public Map<String, Object> shareBattle(Long battleId, Long senderUserId, Long receiverUserId) {
        initTables();
        requireBattle(battleId);
        if (senderUserId == null || receiverUserId == null || senderUserId.equals(receiverUserId)) {
            throw new ResponseStatusException(BAD_REQUEST, "怨듭쑀 ??곸씠 ?щ컮瑜댁???딆뒿?덈떎.");
        }
        Integer mutual = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM user_follow f1
                JOIN user_follow f2
                  ON f2.follower_user_id = f1.following_user_id
                 AND f2.following_user_id = f1.follower_user_id
                WHERE f1.follower_user_id = ?
                  AND f1.following_user_id = ?
                """, Integer.class, senderUserId, receiverUserId);
        if (mutual == null || mutual == 0) {
            throw new ResponseStatusException(BAD_REQUEST, "Only mutual followers can receive shared battles.");
        }
        jdbcTemplate.update("""
                INSERT INTO battle_share (battle_id, sender_user_id, receiver_user_id)
                VALUES (?, ?, ?)
                """, battleId, senderUserId, receiverUserId);

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("shared", true);
        result.put("battleId", battleId);
        result.put("receiverUserId", receiverUserId);
        return result;
    }

    private void incrementVote(Long battleId, String option) {
        jdbcTemplate.update("UPDATE movie_battle SET " + voteColumn(option) + " = " + voteColumn(option) + " + 1 WHERE id = ?", battleId);
    }

    private void decrementVote(Long battleId, String option) {
        jdbcTemplate.update("UPDATE movie_battle SET " + voteColumn(option) + " = GREATEST(0, " + voteColumn(option) + " - 1) WHERE id = ?", battleId);
    }

    private String voteColumn(String option) {
        return "A".equals(option) ? "vote_a" : "vote_b";
    }

    private void requireMovie(Long movieId) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM movie WHERE id = ?", Integer.class, movieId);
        if (count == null || count == 0) {
            throw new ResponseStatusException(BAD_REQUEST, "선택한 영화를 찾을 수 없습니다.");
        }
    }

    private void requireBattle(Long battleId) {
        Integer count = jdbcTemplate.queryForObject("SELECT COUNT(*) FROM movie_battle WHERE id = ?", Integer.class, battleId);
        if (count == null || count == 0) {
            throw new ResponseStatusException(NOT_FOUND, "배틀을 찾을 수 없습니다.");
        }
    }

    private String requireText(String value, String message, int maxLength) {
        String normalized = value == null ? "" : value.trim();
        if (normalized.isBlank()) {
            throw new ResponseStatusException(BAD_REQUEST, message);
        }
        if (normalized.length() > maxLength) {
            throw new ResponseStatusException(BAD_REQUEST, maxLength + "자 이하로 입력해주세요.");
        }
        return normalized;
    }

    private Map<String, Object> fetchResult(Long battleId, String myVote) {
        return jdbcTemplate.query(
                "SELECT vote_a, vote_b FROM movie_battle WHERE id = ?",
                rs -> {
                    if (!rs.next()) return Map.of();
                    int va = rs.getInt("vote_a");
                    int vb = rs.getInt("vote_b");
                    int total = va + vb;
                    Map<String, Object> r = new LinkedHashMap<>();
                    r.put("voteA", va);
                    r.put("voteB", vb);
                    r.put("pctA", total > 0 ? Math.round(va * 100.0 / total) : 50);
                    r.put("pctB", total > 0 ? Math.round(vb * 100.0 / total) : 50);
                    r.put("myVote", myVote);
                    return r;
                }, battleId);
    }

    private Map<String, Object> fetchComment(Long commentId, Long currentUserId) {
        return jdbcTemplate.query("""
                SELECT bc.id AS comment_id, bc.content, bc.created_at,
                       u.id AS user_id, u.login_id, u.nickname, u.profile_image_url,
                       (SELECT COUNT(*) FROM battle_comment_like bcl WHERE bcl.comment_id = bc.id) AS like_count,
                       CASE WHEN EXISTS (
                           SELECT 1 FROM battle_comment_like bcl
                           WHERE bcl.comment_id = bc.id AND bcl.user_id = ?
                       ) THEN TRUE ELSE FALSE END AS liked_by_me
                FROM battle_comment bc
                JOIN "USER" u ON u.id = bc.user_id
                WHERE bc.id = ?
                """, rs -> rs.next() ? mapCommentRow(
                rs.getLong("comment_id"),
                rs.getString("content"),
                rs.getTimestamp("created_at"),
                rs.getLong("user_id"),
                rs.getString("login_id"),
                rs.getString("nickname"),
                rs.getString("profile_image_url"),
                rs.getInt("like_count"),
                rs.getBoolean("liked_by_me"),
                currentUserId) : Map.of(), currentUserId == null ? -1L : currentUserId, commentId);
    }

    private Integer countComments(Long battleId) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM battle_comment WHERE battle_id = ?",
                Integer.class,
                battleId);
        return count == null ? 0 : count;
    }

    private Integer countCommentLikes(Long commentId) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM battle_comment_like WHERE comment_id = ?",
                Integer.class,
                commentId);
        return count == null ? 0 : count;
    }

    private Map<String, Object> fetchTopComment(Long battleId) {
        Map<String, Object> topComment = jdbcTemplate.query("""
                SELECT bc.id AS comment_id, bc.content, bc.created_at,
                       u.id AS user_id, u.login_id, u.nickname, u.profile_image_url,
                       (SELECT COUNT(*) FROM battle_comment_like bcl WHERE bcl.comment_id = bc.id) AS like_count
                FROM battle_comment bc
                JOIN "USER" u ON u.id = bc.user_id
                WHERE bc.battle_id = ?
                ORDER BY like_count DESC, bc.created_at ASC
                LIMIT 1
                """, rs -> rs.next() ? mapCommentRow(
                rs.getLong("comment_id"),
                rs.getString("content"),
                rs.getTimestamp("created_at"),
                rs.getLong("user_id"),
                rs.getString("login_id"),
                rs.getString("nickname"),
                rs.getString("profile_image_url"),
                rs.getInt("like_count"),
                false,
                null) : null, battleId);
        return topComment == null ? Map.of() : topComment;
    }

    private Map<String, Object> mapCommentRow(Long commentId,
                                              String content,
                                              Timestamp createdAt,
                                              Long userId,
                                              String loginId,
                                              String nickname,
                                              String profileImageUrl,
                                              int likeCount,
                                              boolean likedByMe,
                                              Long currentUserId) {
        Map<String, Object> comment = new LinkedHashMap<>();
        comment.put("commentId", commentId);
        comment.put("content", content);
        comment.put("createdAt", createdAt == null ? "" : createdAt.toLocalDateTime().toString());
        comment.put("userId", userId);
        comment.put("loginId", loginId);
        comment.put("nickname", nickname);
        comment.put("profileImageUrl", profileImageUrl);
        comment.put("likeCount", likeCount);
        comment.put("likedByMe", likedByMe);
        comment.put("isMyComment", currentUserId != null && userId != null && userId.longValue() == currentUserId.longValue());
        return comment;
    }

    private Map<String, Object> toBattleRow(ResultSet rs) throws SQLException {
        int va = rs.getInt("vote_a");
        int vb = rs.getInt("vote_b");
        boolean hasMovieB = rs.getObject("movie_b_id") != null;
        int total = va + vb;

        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", rs.getLong("id"));
        row.put("creatorUserId", rs.getObject("creator_user_id"));
        row.put("creatorLoginId", rs.getString("creator_login_id"));
        row.put("creatorNickname", rs.getString("creator_nickname"));
        row.put("battleType", rs.getString("battle_type"));
        row.put("battleLabel", rs.getString("battle_label"));
        row.put("optionALabel", firstNonBlank(rs.getString("option_a_label"), rs.getString("movie_a_title")));
        row.put("optionBLabel", firstNonBlank(rs.getString("option_b_label"), rs.getString("movie_b_title"), "선택지 B"));
        row.put("optionAImageUrl", firstNonBlank(rs.getString("option_a_image_url"), rs.getString("movie_a_poster")));
        row.put("optionBImageUrl", firstNonBlank(rs.getString("option_b_image_url"), rs.getString("movie_b_poster")));
        row.put("voteA", va);
        row.put("voteB", vb);
        row.put("pctA", total > 0 ? Math.round(va * 100.0 / total) : 50);
        row.put("pctB", total > 0 ? Math.round(vb * 100.0 / total) : 50);
        row.put("hasMovieB", hasMovieB);
        row.put("createdAt", rs.getString("created_at"));

        row.put("movieAId", rs.getLong("movie_a_id"));
        row.put("movieACode", rs.getString("movie_a_code"));
        row.put("movieATitle", rs.getString("movie_a_title"));
        row.put("movieAPoster", rs.getString("movie_a_poster"));
        row.put("movieARating", rs.getDouble("movie_a_rating"));

        if (hasMovieB) {
            row.put("movieBId", rs.getLong("movie_b_id"));
            row.put("movieBCode", rs.getString("movie_b_code"));
            row.put("movieBTitle", rs.getString("movie_b_title"));
            row.put("movieBPoster", rs.getString("movie_b_poster"));
            row.put("movieBRating", rs.getDouble("movie_b_rating"));
        }

        row.put("myVote", rs.getString("my_vote"));
        return row;
    }

    private String firstNonBlank(String... values) {
        for (String value : values) {
            if (value != null && !value.isBlank()) return value;
        }
        return "";
    }

    private void addColumnIfMissing(String table, String column, String definition) {
        try {
            jdbcTemplate.execute("ALTER TABLE " + table + " ADD COLUMN IF NOT EXISTS " + column + " " + definition);
        } catch (Exception ignored) {
        }
    }

    private void allowNullableMovieB() {
        try {
            jdbcTemplate.execute("ALTER TABLE movie_battle ALTER COLUMN movie_b_id DROP NOT NULL");
        } catch (Exception ignored) {
        }
    }

    private void allowNullableVotedMovie() {
        try {
            jdbcTemplate.execute("ALTER TABLE battle_vote ALTER COLUMN voted_movie_id DROP NOT NULL");
        } catch (Exception ignored) {
        }
    }
}
