package com.cinematch.battle;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.springframework.http.HttpStatus.BAD_REQUEST;
import static org.springframework.http.HttpStatus.NOT_FOUND;

@Service
public class MovieBattleService {

    private final JdbcTemplate jdbcTemplate;

    public MovieBattleService(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    // ── 테이블 초기화 (기존 DB에 테이블이 없을 경우 자동 생성) ──────────────────

    public void initTables() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS movie_battle (
                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    movie_a_id   BIGINT NOT NULL,
                    movie_b_id   BIGINT NOT NULL,
                    battle_type  VARCHAR(20)  NOT NULL,
                    battle_label VARCHAR(200),
                    vote_a       INT NOT NULL DEFAULT 0,
                    vote_b       INT NOT NULL DEFAULT 0,
                    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_battle_a    FOREIGN KEY (movie_a_id) REFERENCES movie(id),
                    CONSTRAINT fk_battle_b    FOREIGN KEY (movie_b_id) REFERENCES movie(id),
                    CONSTRAINT uq_battle_pair UNIQUE (movie_a_id, movie_b_id)
                )
                """);
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS battle_vote (
                    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    battle_id      BIGINT NOT NULL,
                    user_id        BIGINT NOT NULL,
                    voted_movie_id BIGINT NOT NULL,
                    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bvote_battle FOREIGN KEY (battle_id)      REFERENCES movie_battle(id),
                    CONSTRAINT fk_bvote_user   FOREIGN KEY (user_id)        REFERENCES "USER"(id),
                    CONSTRAINT fk_bvote_movie  FOREIGN KEY (voted_movie_id) REFERENCES movie(id),
                    CONSTRAINT uq_battle_user  UNIQUE (battle_id, user_id)
                )
                """);
    }

    // ── 조회 ─────────────────────────────────────────────────────────────────

    public List<Map<String, Object>> getActiveBattles(Long currentUserId) {
        initTables();
        return jdbcTemplate.query("""
                SELECT b.id, b.battle_type, b.battle_label, b.vote_a, b.vote_b, b.created_at,
                       ma.id AS movie_a_id, ma.movie_cd AS movie_a_code,
                       COALESCE(ma.title, ma.movie_name) AS movie_a_title,
                       ma.poster_image_url AS movie_a_poster,
                       COALESCE(ma.vote_average, 0) AS movie_a_rating,
                       mb.id AS movie_b_id, mb.movie_cd AS movie_b_code,
                       COALESCE(mb.title, mb.movie_name) AS movie_b_title,
                       mb.poster_image_url AS movie_b_poster,
                       COALESCE(mb.vote_average, 0) AS movie_b_rating,
                       bv.voted_movie_id AS my_vote
                FROM movie_battle b
                JOIN movie ma ON ma.id = b.movie_a_id
                JOIN movie mb ON mb.id = b.movie_b_id
                LEFT JOIN battle_vote bv ON bv.battle_id = b.id AND bv.user_id = ?
                ORDER BY b.created_at DESC
                LIMIT 20
                """, (rs, rowNum) -> toBattleRow(rs), currentUserId == null ? -1L : currentUserId);
    }

    // ── 배틀 자동 생성 ────────────────────────────────────────────────────────

    /**
     * 5가지 타입(장르/감독/배우/태그/연대) 기반으로 배틀 페어를 자동 생성.
     * 이미 존재하는 페어는 UNIQUE 제약으로 무시됨.
     *
     * @return 새로 생성된 배틀 수
     */
    public int generateBattles() {
        initTables();
        int count = 0;
        count += generateGenreBattles();
        count += generateDirectorBattles();
        count += generateActorBattles();
        count += generateTagBattles();
        count += generateEraBattles();
        return count;
    }

    // 1. 같은 장르, 평점 7.0+, 유사 평점대 (±1.5)
    private int generateGenreBattles() {
        List<Map<String, Object>> candidates = jdbcTemplate.query("""
                SELECT m1.id AS a_id, m2.id AS b_id,
                       CONCAT(g.name, ' 장르 대결') AS label
                FROM movie m1
                JOIN movie_genre mg1 ON mg1.movie_id = m1.id
                JOIN genre g         ON g.id = mg1.genre_id
                JOIN movie_genre mg2 ON mg2.genre_id = g.id
                JOIN movie m2        ON m2.id = mg2.movie_id
                WHERE m1.id < m2.id
                  AND COALESCE(m1.vote_average, 0) >= 7.0
                  AND COALESCE(m2.vote_average, 0) >= 7.0
                  AND ABS(COALESCE(m1.vote_average, 0) - COALESCE(m2.vote_average, 0)) <= 1.5
                  AND COALESCE(m1.popularity, 0) >= 5.0
                  AND COALESCE(m2.popularity, 0) >= 5.0
                  AND NOT EXISTS (
                      SELECT 1 FROM movie_battle
                      WHERE movie_a_id = m1.id AND movie_b_id = m2.id
                  )
                ORDER BY RAND()
                LIMIT 5
                """, (rs, rowNum) -> candidateRow(rs));
        return insertBattles(candidates, "GENRE");
    }

    // 2. 같은 감독의 작품 2개, 둘 다 평점 7.0+
    private int generateDirectorBattles() {
        List<Map<String, Object>> candidates = jdbcTemplate.query("""
                SELECT m1.id AS a_id, m2.id AS b_id,
                       CONCAT(p.name, ' 감독 대결') AS label
                FROM movie_director md1
                JOIN person p          ON p.id = md1.person_id
                JOIN movie_director md2 ON md2.person_id = md1.person_id
                JOIN movie m1          ON m1.id = md1.movie_id
                JOIN movie m2          ON m2.id = md2.movie_id
                WHERE m1.id < m2.id
                  AND COALESCE(m1.vote_average, 0) >= 7.0
                  AND COALESCE(m2.vote_average, 0) >= 7.0
                  AND NOT EXISTS (
                      SELECT 1 FROM movie_battle
                      WHERE movie_a_id = m1.id AND movie_b_id = m2.id
                  )
                ORDER BY RAND()
                LIMIT 3
                """, (rs, rowNum) -> candidateRow(rs));
        return insertBattles(candidates, "DIRECTOR");
    }

    // 3. 같은 배우(상위 3위 이내 크레딧) 출연작 2개, 둘 다 평점 7.0+
    private int generateActorBattles() {
        List<Map<String, Object>> candidates = jdbcTemplate.query("""
                SELECT m1.id AS a_id, m2.id AS b_id,
                       CONCAT(p.name, ' 출연작 대결') AS label
                FROM movie_actor ma1
                JOIN person p        ON p.id = ma1.person_id
                JOIN movie_actor ma2 ON ma2.person_id = ma1.person_id
                JOIN movie m1        ON m1.id = ma1.movie_id
                JOIN movie m2        ON m2.id = ma2.movie_id
                WHERE m1.id < m2.id
                  AND ma1.display_order <= 3
                  AND ma2.display_order <= 3
                  AND COALESCE(m1.vote_average, 0) >= 7.0
                  AND COALESCE(m2.vote_average, 0) >= 7.0
                  AND NOT EXISTS (
                      SELECT 1 FROM movie_battle
                      WHERE movie_a_id = m1.id AND movie_b_id = m2.id
                  )
                ORDER BY RAND()
                LIMIT 3
                """, (rs, rowNum) -> candidateRow(rs));
        return insertBattles(candidates, "ACTOR");
    }

    // 4. 같은 MOOD 태그를 가진 영화 2개, 둘 다 평점 7.0+
    private int generateTagBattles() {
        List<Map<String, Object>> candidates = jdbcTemplate.query("""
                SELECT m1.id AS a_id, m2.id AS b_id,
                       CONCAT('#', t.tag_name, ' 무드 대결') AS label
                FROM movie_tag mt1
                JOIN tag t        ON t.id = mt1.tag_id AND t.tag_type = 'MOOD'
                JOIN movie_tag mt2 ON mt2.tag_id = t.id
                JOIN movie m1     ON m1.id = mt1.movie_id
                JOIN movie m2     ON m2.id = mt2.movie_id
                WHERE m1.id < m2.id
                  AND COALESCE(m1.vote_average, 0) >= 7.0
                  AND COALESCE(m2.vote_average, 0) >= 7.0
                  AND NOT EXISTS (
                      SELECT 1 FROM movie_battle
                      WHERE movie_a_id = m1.id AND movie_b_id = m2.id
                  )
                ORDER BY RAND()
                LIMIT 3
                """, (rs, rowNum) -> candidateRow(rs));
        return insertBattles(candidates, "TAG");
    }

    // 5. 같은 10년대(연도 / 10 * 10), 둘 다 평점 7.5+, 평점 차 ±1.0 이내
    private int generateEraBattles() {
        List<Map<String, Object>> candidates = jdbcTemplate.query("""
                SELECT m1.id AS a_id, m2.id AS b_id,
                       CONCAT((m1.production_year / 10 * 10), '년대 명작 대결') AS label
                FROM movie m1
                JOIN movie m2 ON (m1.production_year / 10) = (m2.production_year / 10)
                WHERE m1.id < m2.id
                  AND m1.production_year IS NOT NULL
                  AND m2.production_year IS NOT NULL
                  AND COALESCE(m1.vote_average, 0) >= 7.5
                  AND COALESCE(m2.vote_average, 0) >= 7.5
                  AND ABS(COALESCE(m1.vote_average, 0) - COALESCE(m2.vote_average, 0)) <= 1.0
                  AND NOT EXISTS (
                      SELECT 1 FROM movie_battle
                      WHERE movie_a_id = m1.id AND movie_b_id = m2.id
                  )
                ORDER BY RAND()
                LIMIT 3
                """, (rs, rowNum) -> candidateRow(rs));
        return insertBattles(candidates, "ERA");
    }

    private int insertBattles(List<Map<String, Object>> candidates, String type) {
        int count = 0;
        for (Map<String, Object> c : candidates) {
            try {
                jdbcTemplate.update(
                        "INSERT INTO movie_battle (movie_a_id, movie_b_id, battle_type, battle_label) VALUES (?, ?, ?, ?)",
                        c.get("aId"), c.get("bId"), type, c.get("label"));
                count++;
            } catch (Exception ignored) {
                // UNIQUE 위반 → 이미 존재하는 페어, 무시
            }
        }
        return count;
    }

    // ── 투표 ──────────────────────────────────────────────────────────────────

    /**
     * 투표 로직:
     * - 처음 투표 → insert
     * - 같은 영화 재클릭 → 취소(delete)
     * - 다른 영화 클릭 → 변경(delete + insert)
     */
    public Map<String, Object> vote(Long battleId, Long movieId, Long userId) {
        initTables();

        // 배틀 존재 및 영화 소속 확인
        Long[] pair = jdbcTemplate.query(
                "SELECT movie_a_id, movie_b_id FROM movie_battle WHERE id = ?",
                rs -> rs.next() ? new Long[]{rs.getLong("movie_a_id"), rs.getLong("movie_b_id")} : null,
                battleId);
        if (pair == null) throw new ResponseStatusException(NOT_FOUND, "배틀을 찾을 수 없습니다.");

        Long aId = pair[0], bId = pair[1];
        if (!movieId.equals(aId) && !movieId.equals(bId)) {
            throw new ResponseStatusException(BAD_REQUEST, "해당 배틀에 포함된 영화가 아닙니다.");
        }

        Long prevVote = jdbcTemplate.query(
                "SELECT voted_movie_id FROM battle_vote WHERE battle_id = ? AND user_id = ?",
                rs -> rs.next() ? rs.getLong("voted_movie_id") : null,
                battleId, userId);

        if (prevVote != null) {
            // 기존 투표 삭제 + 카운터 감소
            jdbcTemplate.update("DELETE FROM battle_vote WHERE battle_id = ? AND user_id = ?", battleId, userId);
            if (prevVote.equals(aId)) {
                jdbcTemplate.update("UPDATE movie_battle SET vote_a = GREATEST(0, vote_a - 1) WHERE id = ?", battleId);
            } else {
                jdbcTemplate.update("UPDATE movie_battle SET vote_b = GREATEST(0, vote_b - 1) WHERE id = ?", battleId);
            }
            if (prevVote.equals(movieId)) {
                // 같은 영화 → 취소만 하고 끝
                return fetchResult(battleId, null);
            }
        }

        // 새 투표 insert + 카운터 증가
        jdbcTemplate.update(
                "INSERT INTO battle_vote (battle_id, user_id, voted_movie_id) VALUES (?, ?, ?)",
                battleId, userId, movieId);
        if (movieId.equals(aId)) {
            jdbcTemplate.update("UPDATE movie_battle SET vote_a = vote_a + 1 WHERE id = ?", battleId);
        } else {
            jdbcTemplate.update("UPDATE movie_battle SET vote_b = vote_b + 1 WHERE id = ?", battleId);
        }
        return fetchResult(battleId, movieId);
    }

    private Map<String, Object> fetchResult(Long battleId, Long myVote) {
        return jdbcTemplate.query(
                "SELECT vote_a, vote_b FROM movie_battle WHERE id = ?",
                rs -> {
                    if (!rs.next()) return Map.of();
                    int va = rs.getInt("vote_a");
                    int vb = rs.getInt("vote_b");
                    int total = va + vb;
                    Map<String, Object> r = new LinkedHashMap<>();
                    r.put("voteA", va);
                    r.put("voteB", vb);
                    r.put("pctA", total > 0 ? Math.round(va * 100.0 / total) : 50);
                    r.put("pctB", total > 0 ? Math.round(vb * 100.0 / total) : 50);
                    r.put("myVote", myVote);
                    return r;
                }, battleId);
    }

    // ── ResultSet 매핑 헬퍼 ───────────────────────────────────────────────────

    private Map<String, Object> candidateRow(ResultSet rs) throws SQLException {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("aId", rs.getLong("a_id"));
        row.put("bId", rs.getLong("b_id"));
        row.put("label", rs.getString("label"));
        return row;
    }

    private Map<String, Object> toBattleRow(ResultSet rs) throws SQLException {
        int va = rs.getInt("vote_a");
        int vb = rs.getInt("vote_b");
        int total = va + vb;

        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", rs.getLong("id"));
        row.put("battleType", rs.getString("battle_type"));
        row.put("battleLabel", rs.getString("battle_label"));
        row.put("voteA", va);
        row.put("voteB", vb);
        row.put("pctA", total > 0 ? Math.round(va * 100.0 / total) : 50);
        row.put("pctB", total > 0 ? Math.round(vb * 100.0 / total) : 50);
        row.put("createdAt", rs.getString("created_at"));

        row.put("movieAId", rs.getLong("movie_a_id"));
        row.put("movieACode", rs.getString("movie_a_code"));
        row.put("movieATitle", rs.getString("movie_a_title"));
        row.put("movieAPoster", rs.getString("movie_a_poster"));
        row.put("movieARating", rs.getDouble("movie_a_rating"));

        row.put("movieBId", rs.getLong("movie_b_id"));
        row.put("movieBCode", rs.getString("movie_b_code"));
        row.put("movieBTitle", rs.getString("movie_b_title"));
        row.put("movieBPoster", rs.getString("movie_b_poster"));
        row.put("movieBRating", rs.getDouble("movie_b_rating"));

        Object myVote = rs.getObject("my_vote");
        row.put("myVote", myVote);
        return row;
    }
}
