spring.application.name=login
spring.profiles.active=local
spring.datasource.url=jdbc:h2:file:./data/kobisdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true
spring.h2.console.settings.trace=false
spring.sql.init.mode=never
kobis.poster-fetch.enabled=true
kobis.base-url=https://www.kobis.or.kr/kobisopenapi/webservice/rest
kobis.api-key=${KOBIS_API_KEY:68f4299aef91f55f83148bd9eb67e69a}
kobis.connect-timeout-ms=5000
kobis.read-timeout-ms=10000
# YouTube Data API v3 (https://console.cloud.google.com 에서 발급)
youtube.api-key=${YOUTUBE_API_KEY:AIzaSyDKvZlFbLPWgSUoUJwZai7u6Ocn5di03Dw}

tmdb.base-url=https://api.themoviedb.org/3
tmdb.token=${TMDB_TOKEN:eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzYjljNDBhYmE4Yzg2ZjM0MjdmY2I1ZTc4Yzg3MDQ0MCIsIm5iZiI6MTc3NDUxMDkxOS4xMDksInN1YiI6IjY5YzRlMzQ3ZmY5N2Y3ZmFmZmI3ZDNjZCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.YXuz8COo1s5B1hrvifQAKWvHNhVCywlUBEcG9GKLt8k}
app.schema-bootstrap.enabled=true
app.csv-init.enabled=true
app.startup-sync.enabled=false
app.startup-sync.import-existing-limit=200
app.startup-sync.kobis-start-year=2016
app.startup-sync.kobis-end-year=2025
app.startup-sync.kobis-target-per-year=20

# 파일 업로드 설정
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

# 업로드 파일 저장 경로 (프로젝트 루트 기준)
app.upload.dir=uploads

# 한글 URL 파라미터 인코딩
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
logging.level.org.springframework.jdbc.core=TRACE
