DROP TABLE IF EXISTS user_movie_life;
DROP TABLE IF EXISTS user_movie_store;
DROP TABLE IF EXISTS user_movie_like;
DROP TABLE IF EXISTS movie_audit;
DROP TABLE IF EXISTS movie_company;
DROP TABLE IF EXISTS movie_provider;
DROP TABLE IF EXISTS movie_keyword;
DROP TABLE IF EXISTS movie_tag;
DROP TABLE IF EXISTS batch_job_run;
DROP TABLE IF EXISTS kobis_movie_raw;
DROP TABLE IF EXISTS tmdb_movie_raw;
DROP TABLE IF EXISTS movie_actor;
DROP TABLE IF EXISTS movie_director;
DROP TABLE IF EXISTS movie_genre;
DROP TABLE IF EXISTS movie_source;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS audit;
DROP TABLE IF EXISTS watch_grade;
DROP TABLE IF EXISTS provider;
DROP TABLE IF EXISTS keyword;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS production_status;
DROP TABLE IF EXISTS movie_type;

CREATE TABLE movie_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE production_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE nation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE provider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_provider_id BIGINT NOT NULL UNIQUE,
    provider_name VARCHAR(255) NOT NULL,
    logo_path VARCHAR(500),
    display_priority INT
);

CREATE TABLE keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_keyword_id BIGINT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE tag (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tag_name VARCHAR(100) NOT NULL,
    tag_type VARCHAR(20) NOT NULL,
    CONSTRAINT uk_tag_name_type UNIQUE (tag_name, tag_type)
);

CREATE TABLE watch_grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_no VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "USER" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(100) NOT NULL UNIQUE,
    login_pw VARCHAR(100) NOT NULL,
    nickname VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    age INT NOT NULL,
    CONSTRAINT ck_user_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ranking INT,
    movie_cd VARCHAR(20) NOT NULL UNIQUE,
    movie_name VARCHAR(255) NOT NULL,
    movie_name_en VARCHAR(255),
    movie_name_original VARCHAR(255),
    box_office_open_date DATE,
    movie_info_open_date DATE,
    production_year INT,
    show_time INT,
    movie_type_id BIGINT,
    production_status_id BIGINT,
    nation_id BIGINT,
    poster_image_url VARCHAR(500),
    box_office_sales_acc BIGINT,
    box_office_audi_acc BIGINT,
    box_office_scrn_cnt INT,
    box_office_show_cnt INT,
    title VARCHAR(255),
    original_title VARCHAR(255),
    overview CLOB,
    release_date DATE,
    runtime INT,
    budget BIGINT,
    revenue BIGINT,
    tmdb_status VARCHAR(100),
    tagline VARCHAR(500),
    poster_path VARCHAR(500),
    backdrop_path VARCHAR(500),
    vote_average DOUBLE PRECISION,
    vote_count INT,
    popularity DOUBLE PRECISION,
    adult BOOLEAN,
    original_language VARCHAR(20),
    homepage VARCHAR(500),
    imdb_id VARCHAR(50),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_movie_type FOREIGN KEY (movie_type_id) REFERENCES movie_type(id),
    CONSTRAINT fk_movie_status FOREIGN KEY (production_status_id) REFERENCES production_status(id),
    CONSTRAINT fk_movie_nation FOREIGN KEY (nation_id) REFERENCES nation(id)
);

CREATE TABLE movie_source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    source_type VARCHAR(20) NOT NULL,
    source_key VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_movie_source_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT uk_movie_source_type_key UNIQUE (source_type, source_key),
    CONSTRAINT uk_movie_source_movie_type UNIQUE (movie_id, source_type)
);

CREATE TABLE movie_genre (
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, genre_id),
    CONSTRAINT fk_movie_genre_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_genre_genre FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE movie_director (
    movie_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, person_id),
    CONSTRAINT fk_movie_director_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_director_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE movie_actor (
    movie_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, person_id),
    CONSTRAINT fk_movie_actor_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_actor_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE movie_company (
    movie_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    company_role VARCHAR(100),
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, company_id, display_order),
    CONSTRAINT fk_movie_company_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_company_company FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE movie_provider (
    movie_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    provider_type VARCHAR(20) NOT NULL,
    region_code VARCHAR(10) NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, provider_id, provider_type, region_code),
    CONSTRAINT fk_movie_provider_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_provider_provider FOREIGN KEY (provider_id) REFERENCES provider(id)
);

CREATE TABLE movie_keyword (
    movie_id BIGINT NOT NULL,
    keyword_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, keyword_id),
    CONSTRAINT fk_movie_keyword_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_keyword_keyword FOREIGN KEY (keyword_id) REFERENCES keyword(id)
);

CREATE TABLE movie_tag (
    movie_id BIGINT NOT NULL,
    tag_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY (movie_id, tag_id),
    CONSTRAINT fk_movie_tag_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_tag_tag FOREIGN KEY (tag_id) REFERENCES tag(id)
);

CREATE TABLE batch_job_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL,
    request_payload CLOB,
    result_payload CLOB,
    error_message CLOB,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP
);

CREATE TABLE kobis_movie_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kobis_movie_cd VARCHAR(20) NOT NULL UNIQUE,
    payload CLOB NOT NULL,
    imported_at TIMESTAMP NOT NULL
);

CREATE TABLE tmdb_movie_raw (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_movie_id BIGINT NOT NULL UNIQUE,
    payload CLOB NOT NULL,
    imported_at TIMESTAMP NOT NULL
);

CREATE TABLE movie_audit (
    movie_id BIGINT NOT NULL,
    audit_id BIGINT NOT NULL,
    watch_grade_id BIGINT,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, audit_id, display_order),
    CONSTRAINT fk_movie_audit_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_audit_audit FOREIGN KEY (audit_id) REFERENCES audit(id),
    CONSTRAINT fk_movie_audit_watch_grade FOREIGN KEY (watch_grade_id) REFERENCES watch_grade(id)
);

CREATE TABLE user_movie_like (
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    liked BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_user_movie_like_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_user_movie_like_movie FOREIGN KEY (movie_id) REFERENCES movie(id)
);

CREATE TABLE user_movie_store (
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_user_movie_store_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_user_movie_store_movie FOREIGN KEY (movie_id) REFERENCES movie(id)
);

CREATE TABLE user_movie_life (
    user_id BIGINT NOT NULL,
    movie_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, movie_id),
    CONSTRAINT fk_user_movie_life_user FOREIGN KEY (user_id) REFERENCES "USER"(id),
    CONSTRAINT fk_user_movie_life_movie FOREIGN KEY (movie_id) REFERENCES movie(id)
);
