package movie.web.login.kobis;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import tools.jackson.core.JacksonException;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.ObjectMapper;

import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

@Service
public class KobisMovieNormalizeService {

    private static final String SOURCE_TYPE_KOBIS = "KOBIS";
    private static final DateTimeFormatter BASIC_DATE = DateTimeFormatter.BASIC_ISO_DATE;

    private final JdbcTemplate jdbcTemplate;
    private final ObjectMapper objectMapper;

    public KobisMovieNormalizeService(JdbcTemplate jdbcTemplate, ObjectMapper objectMapper) {
        this.jdbcTemplate = jdbcTemplate;
        this.objectMapper = objectMapper;
    }

    @Transactional
    public NormalizeResult normalizeRawMovies() {
        initializeRawTable();

        List<RawMovieRow> rawMovies = jdbcTemplate.query("""
                SELECT kobis_movie_cd, payload
                FROM kobis_movie_raw
                ORDER BY kobis_movie_cd
                """, (rs, rowNum) -> new RawMovieRow(
                rs.getString("kobis_movie_cd"),
                rs.getString("payload")
        ));

        int processedCount = 0;
        int insertedMovieCount = 0;
        int updatedMovieCount = 0;
        int matchedExistingMovieCount = 0;
        int insertedSourceCount = 0;

        for (RawMovieRow rawMovie : rawMovies) {
            JsonNode root = readTree(rawMovie.payload());
            if (root == null) {
                continue;
            }

            JsonNode weeklyBoxOffice = root.path("weeklyBoxOffice");
            JsonNode movieInfo = root.path("movieInfo");
            if (movieInfo.isMissingNode() || movieInfo.isNull()) {
                continue;
            }

            processedCount++;
            Long movieId = findMovieIdBySource(rawMovie.kobisMovieCd());
            boolean matchedExistingMovie = false;

            if (movieId == null) {
                movieId = findMovieIdByMovieCode(rawMovie.kobisMovieCd());
            }

            if (movieId == null) {
                movieId = findMovieIdByTitle(
                        textValue(movieInfo, "movieNm"),
                        textValue(movieInfo, "movieNmOg"),
                        "TMDB",
                        SOURCE_TYPE_KOBIS
                );
                matchedExistingMovie = movieId != null;
            }

            if (movieId == null) {
                movieId = findMovieIdByTitleAndReleaseDate(
                        textValue(movieInfo, "movieNm"),
                        textValue(movieInfo, "movieNmOg"),
                        parseDate(textValue(movieInfo, "openDt"))
                );
                matchedExistingMovie = movieId != null;
            }

            if (movieId == null) {
                movieId = insertMovie(rawMovie.kobisMovieCd(), weeklyBoxOffice, movieInfo);
                insertedMovieCount++;
            } else {
                updateMovie(movieId, rawMovie.kobisMovieCd(), weeklyBoxOffice, movieInfo);
                updatedMovieCount++;
                if (matchedExistingMovie) {
                    matchedExistingMovieCount++;
                }
            }

            if (upsertMovieSource(movieId, rawMovie.kobisMovieCd())) {
                insertedSourceCount++;
            }

            normalizeGenres(movieId, movieInfo.path("genres"));
            normalizeDirectors(movieId, movieInfo.path("directors"));
            normalizeActors(movieId, movieInfo.path("actors"));
            normalizeCompanies(movieId, movieInfo.path("companys"));
            normalizeAudits(movieId, movieInfo.path("audits"));
        }

        return new NormalizeResult(
                processedCount,
                insertedMovieCount,
                updatedMovieCount,
                matchedExistingMovieCount,
                insertedSourceCount
        );
    }

    private void initializeRawTable() {
        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS kobis_movie_raw (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    kobis_movie_cd VARCHAR(20) NOT NULL UNIQUE,
                    payload CLOB NOT NULL,
                    imported_at TIMESTAMP NOT NULL
                )
                """);
    }

    private Long findMovieIdBySource(String movieCd) {
        return jdbcTemplate.query("""
                SELECT movie_id
                FROM movie_source
                WHERE source_type = ? AND source_key = ?
                """, rs -> rs.next() ? rs.getLong("movie_id") : null, SOURCE_TYPE_KOBIS, movieCd);
    }

    private Long findMovieIdByMovieCode(String movieCd) {
        return jdbcTemplate.query("""
                SELECT id
                FROM movie
                WHERE movie_cd = ?
                """, rs -> rs.next() ? rs.getLong("id") : null, movieCd);
    }

    private Long findMovieIdByTitleAndReleaseDate(String movieName, String originalTitle, LocalDate openDate) {
        if (movieName == null || openDate == null) {
            return null;
        }

        return jdbcTemplate.query("""
                SELECT id
                FROM movie
                WHERE COALESCE(release_date, movie_info_open_date) = ?
                  AND id NOT IN (
                        SELECT movie_id
                        FROM movie_source
                        WHERE source_type = ?
                  )
                  AND (
                        movie_name = ?
                     OR title = ?
                     OR movie_name_original = ?
                     OR original_title = ?
                  )
                ORDER BY id
                LIMIT 1
                """, rs -> rs.next() ? rs.getLong("id") : null,
                Date.valueOf(openDate), SOURCE_TYPE_KOBIS, movieName, movieName, originalTitle, originalTitle);
    }

    private Long findMovieIdByTitle(String movieName, String originalTitle, String preferredSourceType, String currentSourceType) {
        if ((movieName == null || movieName.isBlank()) && (originalTitle == null || originalTitle.isBlank())) {
            return null;
        }

        return jdbcTemplate.query("""
                SELECT m.id
                FROM movie m
                LEFT JOIN movie_source preferred_ms
                    ON preferred_ms.movie_id = m.id
                   AND preferred_ms.source_type = ?
                LEFT JOIN movie_source current_ms
                    ON current_ms.movie_id = m.id
                   AND current_ms.source_type = ?
                WHERE current_ms.id IS NULL
                  AND (
                        (? IS NOT NULL AND (m.movie_name = ? OR m.title = ?))
                     OR (? IS NOT NULL AND (m.movie_name_original = ? OR m.original_title = ?))
                  )
                ORDER BY
                    CASE WHEN preferred_ms.id IS NOT NULL THEN 0 ELSE 1 END,
                    CASE
                        WHEN ? IS NOT NULL AND (m.movie_name = ? OR m.title = ?) THEN 0
                        WHEN ? IS NOT NULL AND (m.movie_name_original = ? OR m.original_title = ?) THEN 1
                        ELSE 2
                    END,
                    m.id
                LIMIT 1
                """, rs -> rs.next() ? rs.getLong("id") : null,
                preferredSourceType,
                currentSourceType,
                movieName, movieName, movieName,
                originalTitle, originalTitle, originalTitle,
                movieName, movieName, movieName,
                originalTitle, originalTitle, originalTitle
        );
    }

    private Long insertMovie(String movieCd, JsonNode weeklyBoxOffice, JsonNode movieInfo) {
        LocalDate openDate = parseDate(textValue(movieInfo, "openDt"));
        LocalDateTime now = LocalDateTime.now();
        Long movieTypeId = resolveLookupId("movie_type", textValue(movieInfo, "typeNm"));
        Long productionStatusId = resolveLookupId("production_status", textValue(movieInfo, "prdtStatNm"));
        Long nationId = resolveLookupId("nation", firstNestedText(movieInfo.path("nations"), "nationNm"));

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO movie (
                        ranking,
                        movie_cd,
                        movie_name,
                        movie_name_en,
                        movie_name_original,
                        box_office_open_date,
                        movie_info_open_date,
                        production_year,
                        show_time,
                        movie_type_id,
                        production_status_id,
                        nation_id,
                        poster_image_url,
                        box_office_sales_acc,
                        box_office_audi_acc,
                        box_office_scrn_cnt,
                        box_office_show_cnt,
                        title,
                        original_title,
                        release_date,
                        runtime,
                        created_at,
                        updated_at
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                    """, Statement.RETURN_GENERATED_KEYS);
            statement.setObject(1, parseInteger(textValue(weeklyBoxOffice, "rank")));
            statement.setString(2, movieCd);
            statement.setString(3, textValue(movieInfo, "movieNm"));
            statement.setString(4, textValue(movieInfo, "movieNmEn"));
            statement.setString(5, textValue(movieInfo, "movieNmOg"));
            statement.setDate(6, toSqlDate(parseDate(textValue(weeklyBoxOffice, "openDt"))));
            statement.setDate(7, toSqlDate(openDate));
            statement.setObject(8, parseInteger(textValue(movieInfo, "prdtYear")));
            statement.setObject(9, parseInteger(textValue(movieInfo, "showTm")));
            statement.setObject(10, movieTypeId);
            statement.setObject(11, productionStatusId);
            statement.setObject(12, nationId);
            statement.setString(13, null);
            statement.setObject(14, parseLong(textValue(weeklyBoxOffice, "salesAcc")));
            statement.setObject(15, parseLong(textValue(weeklyBoxOffice, "audiAcc")));
            statement.setObject(16, parseInteger(textValue(weeklyBoxOffice, "scrnCnt")));
            statement.setObject(17, parseInteger(textValue(weeklyBoxOffice, "showCnt")));
            statement.setString(18, textValue(movieInfo, "movieNm"));
            statement.setString(19, textValue(movieInfo, "movieNmOg"));
            statement.setDate(20, toSqlDate(openDate));
            statement.setObject(21, parseInteger(textValue(movieInfo, "showTm")));
            statement.setTimestamp(22, Timestamp.valueOf(now));
            statement.setTimestamp(23, Timestamp.valueOf(now));
            return statement;
        }, keyHolder);
        return keyHolder.getKeyAs(Long.class);
    }

    private void updateMovie(Long movieId, String movieCd, JsonNode weeklyBoxOffice, JsonNode movieInfo) {
        LocalDate openDate = parseDate(textValue(movieInfo, "openDt"));
        jdbcTemplate.update("""
                UPDATE movie
                SET ranking = COALESCE(?, ranking),
                    movie_cd = COALESCE(movie_cd, ?),
                    movie_name = COALESCE(movie_name, ?),
                    movie_name_en = COALESCE(movie_name_en, ?),
                    movie_name_original = COALESCE(movie_name_original, ?),
                    box_office_open_date = COALESCE(box_office_open_date, ?),
                    movie_info_open_date = COALESCE(movie_info_open_date, ?),
                    production_year = COALESCE(production_year, ?),
                    show_time = COALESCE(show_time, ?),
                    movie_type_id = COALESCE(movie_type_id, ?),
                    production_status_id = COALESCE(production_status_id, ?),
                    nation_id = COALESCE(nation_id, ?),
                    box_office_sales_acc = COALESCE(box_office_sales_acc, ?),
                    box_office_audi_acc = COALESCE(box_office_audi_acc, ?),
                    box_office_scrn_cnt = COALESCE(box_office_scrn_cnt, ?),
                    box_office_show_cnt = COALESCE(box_office_show_cnt, ?),
                    title = COALESCE(title, ?),
                    original_title = COALESCE(original_title, ?),
                    release_date = COALESCE(release_date, ?),
                    runtime = COALESCE(runtime, ?),
                    updated_at = ?
                WHERE id = ?
                """,
                parseInteger(textValue(weeklyBoxOffice, "rank")),
                movieCd,
                textValue(movieInfo, "movieNm"),
                textValue(movieInfo, "movieNmEn"),
                textValue(movieInfo, "movieNmOg"),
                toSqlDate(parseDate(textValue(weeklyBoxOffice, "openDt"))),
                toSqlDate(openDate),
                parseInteger(textValue(movieInfo, "prdtYear")),
                parseInteger(textValue(movieInfo, "showTm")),
                resolveLookupId("movie_type", textValue(movieInfo, "typeNm")),
                resolveLookupId("production_status", textValue(movieInfo, "prdtStatNm")),
                resolveLookupId("nation", firstNestedText(movieInfo.path("nations"), "nationNm")),
                parseLong(textValue(weeklyBoxOffice, "salesAcc")),
                parseLong(textValue(weeklyBoxOffice, "audiAcc")),
                parseInteger(textValue(weeklyBoxOffice, "scrnCnt")),
                parseInteger(textValue(weeklyBoxOffice, "showCnt")),
                textValue(movieInfo, "movieNm"),
                textValue(movieInfo, "movieNmOg"),
                toSqlDate(openDate),
                parseInteger(textValue(movieInfo, "showTm")),
                Timestamp.valueOf(LocalDateTime.now()),
                movieId
        );
    }

    private boolean upsertMovieSource(Long movieId, String movieCd) {
        Integer existingCount = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM movie_source
                WHERE source_type = ? AND source_key = ?
                """, Integer.class, SOURCE_TYPE_KOBIS, movieCd);

        if (existingCount != null && existingCount > 0) {
            jdbcTemplate.update("""
                    UPDATE movie_source
                    SET movie_id = ?, updated_at = ?
                    WHERE source_type = ? AND source_key = ?
                    """, movieId, Timestamp.valueOf(LocalDateTime.now()), SOURCE_TYPE_KOBIS, movieCd);
            return false;
        }

        LocalDateTime now = LocalDateTime.now();
        jdbcTemplate.update("""
                INSERT INTO movie_source (movie_id, source_type, source_key, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?)
                """, movieId, SOURCE_TYPE_KOBIS, movieCd, Timestamp.valueOf(now), Timestamp.valueOf(now));
        return true;
    }

    private void normalizeGenres(Long movieId, JsonNode genresNode) {
        for (String genreName : collectDistinctNames(genresNode, "genreNm")) {
            Long genreId = resolveLookupId("genre", canonicalGenreName(genreName));
            if (genreId != null && !existsLink("movie_genre", "movie_id", movieId, "genre_id", genreId)) {
                jdbcTemplate.update("""
                        INSERT INTO movie_genre (movie_id, genre_id, display_order)
                        VALUES (?, ?, ?)
                        """, movieId, genreId, nextDisplayOrder("movie_genre", movieId));
            }
        }
    }

    private void normalizeDirectors(Long movieId, JsonNode directorsNode) {
        for (String directorName : collectDistinctNames(directorsNode, "peopleNm")) {
            Long personId = resolveLookupId("person", directorName);
            if (personId != null && !existsLink("movie_director", "movie_id", movieId, "person_id", personId)) {
                jdbcTemplate.update("""
                        INSERT INTO movie_director (movie_id, person_id, display_order)
                        VALUES (?, ?, ?)
                        """, movieId, personId, nextDisplayOrder("movie_director", movieId));
            }
        }
    }

    private void normalizeActors(Long movieId, JsonNode actorsNode) {
        for (String actorName : collectDistinctNames(actorsNode, "peopleNm")) {
            Long personId = resolveLookupId("person", actorName);
            if (personId != null && !existsLink("movie_actor", "movie_id", movieId, "person_id", personId)) {
                jdbcTemplate.update("""
                        INSERT INTO movie_actor (movie_id, person_id, display_order)
                        VALUES (?, ?, ?)
                        """, movieId, personId, nextDisplayOrder("movie_actor", movieId));
            }
        }
    }

    private void normalizeCompanies(Long movieId, JsonNode companiesNode) {
        if (!companiesNode.isArray()) {
            return;
        }

        Set<String> insertedKeys = new LinkedHashSet<>();
        for (JsonNode companyNode : companiesNode) {
            String companyName = textValue(companyNode, "companyNm");
            String companyRole = textValue(companyNode, "companyPartNm");
            if (companyName == null) {
                continue;
            }

            Long companyId = resolveLookupId("company", companyName);
            String dedupeKey = companyId + "|" + companyRole;
            if (companyId == null || insertedKeys.contains(dedupeKey)) {
                continue;
            }
            insertedKeys.add(dedupeKey);

            Integer existingCount = jdbcTemplate.queryForObject("""
                    SELECT COUNT(*)
                    FROM movie_company
                    WHERE movie_id = ? AND company_id = ? AND COALESCE(company_role, '') = COALESCE(?, '')
                    """, Integer.class, movieId, companyId, companyRole);
            if (existingCount != null && existingCount > 0) {
                continue;
            }

            jdbcTemplate.update("""
                    INSERT INTO movie_company (movie_id, company_id, company_role, display_order)
                    VALUES (?, ?, ?, ?)
                    """, movieId, companyId, companyRole, nextDisplayOrder("movie_company", movieId));
        }
    }

    private void normalizeAudits(Long movieId, JsonNode auditsNode) {
        if (!auditsNode.isArray()) {
            return;
        }

        for (JsonNode auditNode : auditsNode) {
            String auditNo = textValue(auditNode, "auditNo");
            String watchGradeName = textValue(auditNode, "watchGradeNm");
            Long auditId = resolveAuditId(auditNo);
            Long watchGradeId = resolveLookupId("watch_grade", watchGradeName);
            if (auditId == null) {
                continue;
            }

            Integer existingCount = jdbcTemplate.queryForObject("""
                    SELECT COUNT(*)
                    FROM movie_audit
                    WHERE movie_id = ?
                      AND audit_id = ?
                      AND COALESCE(watch_grade_id, -1) = COALESCE(?, -1)
                    """, Integer.class, movieId, auditId, watchGradeId);
            if (existingCount != null && existingCount > 0) {
                continue;
            }

            jdbcTemplate.update("""
                    INSERT INTO movie_audit (movie_id, audit_id, watch_grade_id, display_order)
                    VALUES (?, ?, ?, ?)
                    """, movieId, auditId, watchGradeId, nextDisplayOrder("movie_audit", movieId));
        }
    }

    private Long resolveLookupId(String tableName, String value) {
        if (value == null || value.isBlank()) {
            return null;
        }

        Long existingId = jdbcTemplate.query("""
                SELECT id
                FROM %s
                WHERE name = ?
                """.formatted(tableName), rs -> rs.next() ? rs.getLong("id") : null, value);
        if (existingId != null) {
            return existingId;
        }

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO %s (name)
                    VALUES (?)
                    """.formatted(tableName), Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, value);
            return statement;
        }, keyHolder);
        return keyHolder.getKeyAs(Long.class);
    }

    private String canonicalGenreName(String genreName) {
        if (genreName == null || genreName.isBlank()) {
            return genreName;
        }

        return switch (genreName.trim()) {
            case "멜로/로맨스" -> "로맨스";
            case "공포(호러)" -> "공포";
            case "어드벤처" -> "모험";
            default -> genreName.trim();
        };
    }

    private Long resolveAuditId(String auditNo) {
        if (auditNo == null || auditNo.isBlank()) {
            return null;
        }

        Long existingId = jdbcTemplate.query("""
                SELECT id
                FROM audit
                WHERE audit_no = ?
                """, rs -> rs.next() ? rs.getLong("id") : null, auditNo);
        if (existingId != null) {
            return existingId;
        }

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement("""
                    INSERT INTO audit (audit_no)
                    VALUES (?)
                    """, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, auditNo);
            return statement;
        }, keyHolder);
        return keyHolder.getKeyAs(Long.class);
    }

    private boolean existsLink(String tableName, String leftColumnName, Long leftId, String rightColumnName, Long rightId) {
        Integer count = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM %s
                WHERE %s = ? AND %s = ?
                """.formatted(tableName, leftColumnName, rightColumnName), Integer.class, leftId, rightId);
        return count != null && count > 0;
    }

    private int nextDisplayOrder(String tableName, Long movieId) {
        Integer maxDisplayOrder = jdbcTemplate.queryForObject("""
                SELECT COALESCE(MAX(display_order), 0)
                FROM %s
                WHERE movie_id = ?
                """.formatted(tableName), Integer.class, movieId);
        return (maxDisplayOrder == null ? 0 : maxDisplayOrder) + 1;
    }

    private List<String> collectDistinctNames(JsonNode arrayNode, String fieldName) {
        Set<String> values = new LinkedHashSet<>();
        if (!arrayNode.isArray()) {
            return List.of();
        }
        for (JsonNode node : arrayNode) {
            String value = textValue(node, fieldName);
            if (value != null) {
                values.add(value);
            }
        }
        return values.stream().toList();
    }

    private JsonNode readTree(String payload) {
        try {
            return payload == null ? null : objectMapper.readTree(payload);
        } catch (JacksonException e) {
            throw new IllegalStateException("KOBIS raw payload JSON parsing failed.", e);
        }
    }

    private String textValue(JsonNode node, String fieldName) {
        JsonNode value = node.get(fieldName);
        if (value == null || value.isNull()) {
            return null;
        }
        String text = value.asText();
        return text.isBlank() ? null : text;
    }

    private String firstNestedText(JsonNode arrayNode, String fieldName) {
        if (!arrayNode.isArray() || arrayNode.isEmpty()) {
            return null;
        }
        return textValue(arrayNode.get(0), fieldName);
    }

    private Integer parseInteger(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return Integer.valueOf(value);
    }

    private Long parseLong(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return Long.valueOf(value);
    }

    private LocalDate parseDate(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }

        try {
            return value.contains("-") ? LocalDate.parse(value) : LocalDate.parse(value, BASIC_DATE);
        } catch (DateTimeParseException e) {
            return null;
        }
    }

    private Date toSqlDate(LocalDate value) {
        return value == null ? null : Date.valueOf(value);
    }

    private record RawMovieRow(String kobisMovieCd, String payload) {
    }

    public record NormalizeResult(
            int processedCount,
            int insertedMovieCount,
            int updatedMovieCount,
            int matchedExistingMovieCount,
            int insertedSourceCount
    ) {
    }
}
