DROP TABLE IF EXISTS movie_audit;
DROP TABLE IF EXISTS movie_company;
DROP TABLE IF EXISTS movie_actor;
DROP TABLE IF EXISTS movie_director;
DROP TABLE IF EXISTS movie_genre;
DROP TABLE IF EXISTS movie;
DROP TABLE IF EXISTS "USER";
DROP TABLE IF EXISTS audit;
DROP TABLE IF EXISTS watch_grade;
DROP TABLE IF EXISTS company;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS nation;
DROP TABLE IF EXISTS production_status;
DROP TABLE IF EXISTS movie_type;

CREATE TABLE movie_type (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE production_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE nation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE genre (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE person (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE company (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE watch_grade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    audit_no VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE "USER" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login_id VARCHAR(100) NOT NULL UNIQUE,
    login_pw VARCHAR(100) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    age INT NOT NULL,
    CONSTRAINT ck_user_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ranking INT,
    movie_cd VARCHAR(20) NOT NULL UNIQUE,
    movie_name VARCHAR(255) NOT NULL,
    movie_name_en VARCHAR(255),
    movie_name_original VARCHAR(255),
    box_office_open_date DATE,
    movie_info_open_date DATE,
    production_year INT,
    show_time INT,
    movie_type_id BIGINT,
    production_status_id BIGINT,
    nation_id BIGINT,
    poster_image_url VARCHAR(500),
    box_office_sales_acc BIGINT,
    box_office_audi_acc BIGINT,
    box_office_scrn_cnt INT,
    box_office_show_cnt INT,
    CONSTRAINT fk_movie_type FOREIGN KEY (movie_type_id) REFERENCES movie_type(id),
    CONSTRAINT fk_movie_status FOREIGN KEY (production_status_id) REFERENCES production_status(id),
    CONSTRAINT fk_movie_nation FOREIGN KEY (nation_id) REFERENCES nation(id)
);

CREATE TABLE movie_genre (
    movie_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, genre_id),
    CONSTRAINT fk_movie_genre_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_genre_genre FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE movie_director (
    movie_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, person_id),
    CONSTRAINT fk_movie_director_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_director_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE movie_actor (
    movie_id BIGINT NOT NULL,
    person_id BIGINT NOT NULL,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, person_id),
    CONSTRAINT fk_movie_actor_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_actor_person FOREIGN KEY (person_id) REFERENCES person(id)
);

CREATE TABLE movie_company (
    movie_id BIGINT NOT NULL,
    company_id BIGINT NOT NULL,
    company_role VARCHAR(100),
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, company_id, display_order),
    CONSTRAINT fk_movie_company_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_company_company FOREIGN KEY (company_id) REFERENCES company(id)
);

CREATE TABLE movie_audit (
    movie_id BIGINT NOT NULL,
    audit_id BIGINT NOT NULL,
    watch_grade_id BIGINT,
    display_order INT NOT NULL,
    PRIMARY KEY (movie_id, audit_id, display_order),
    CONSTRAINT fk_movie_audit_movie FOREIGN KEY (movie_id) REFERENCES movie(id),
    CONSTRAINT fk_movie_audit_audit FOREIGN KEY (audit_id) REFERENCES audit(id),
    CONSTRAINT fk_movie_audit_watch_grade FOREIGN KEY (watch_grade_id) REFERENCES watch_grade(id)
);
