package movie.web.login.tag;

import org.springframework.stereotype.Component;

import java.util.List;

@Component
public class DefaultRecommendationTagRules {

    private final List<TagRule> rules = buildRules();

    public List<TagRule> rules() {
        return rules;
    }

    private List<TagRule> buildRules() {
        return List.of(
                funny(),
                tense(),
                dark(),
                emotional(),
                romantic(),
                hopeful(),
                healing(),
                spectacle(),
                creepy(),
                withFamily(),
                withPartner(),
                lateNight(),
                violent(),
                sad(),
                slowBurn(),
                longRunning(),
                investigation(),
                mystery(),
                zombie(),
                disaster(),
                trueStory(),
                comingOfAge(),
                friendship(),
                survival(),
                revenge()
        );
    }

    private TagRule funny() {
        return TagRule.builder(RecommendationTag.FUNNY)
                .positiveGenre(GenreNames.COMEDY, 34)
                .positiveGenre(GenreNames.FAMILY, 0)
                .positiveGenre(GenreNames.ANIMATION, 0)
                .positiveGenre(GenreNames.ROMANCE, 4)
                .negativeGenre(GenreNames.HORROR, 14)
                .negativeGenre(GenreNames.WAR, 8)
                .negativeGenre(GenreNames.DRAMA, 4)
                .negativeGenre(GenreNames.FAMILY, 4)
                .negativeGenre(GenreNames.ANIMATION, 6)
                .positiveKeyword("funny", 18)
                .positiveKeyword("hilarious", 18)
                .positiveKeyword("lighthearted", 14)
                .positiveKeyword("witty", 14)
                .positiveKeyword("playful", 8)
                .positiveKeyword("cheerful", 6)
                .positiveKeyword("joyful", 6)
                .positiveKeyword("absurd", 8)
                .positiveKeyword("romcom", 12)
                .positiveKeyword("buddy comedy", 16)
                .positiveKeyword("dark comedy", 10)
                .positiveKeyword("satire", 12)
                .positiveKeyword("social satire", 12)
                .positiveKeyword("satirical", 12)
                .positiveKeyword("black comedy", 10)
                .positiveKeyword("slapstick", 14)
                .positiveKeyword("screwball comedy", 16)
                .positiveKeyword("mockumentary", 14)
                .positiveKeyword("workplace comedy", 12)
                .negativeKeyword("murder", 16)
                .negativeKeyword("serial killer", 22)
                .negativeKeyword("grief", 14)
                .negativeKeyword("depressing", 16)
                .negativeKeyword("gore", 16)
                .negativeKeyword("talking animal", 12)
                .negativeKeyword("3d animation", 10)
                .negativeKeyword("based on children's book", 10)
                .build();
    }

    private TagRule tense() {
        return TagRule.builder(RecommendationTag.TENSE)
                .positiveGenre(GenreNames.THRILLER, 28)
                .positiveGenre(GenreNames.MYSTERY, 16)
                .positiveGenre(GenreNames.CRIME, 12)
                .positiveGenre(GenreNames.ACTION, 10)
                .positiveGenre(GenreNames.HORROR, 10)
                .negativeGenre(GenreNames.FAMILY, 12)
                .negativeGenre(GenreNames.ANIMATION, 10)
                .negativeGenre(GenreNames.COMEDY, 8)
                .positiveKeyword("suspenseful", 18)
                .positiveKeyword("tense", 18)
                .positiveKeyword("intense", 16)
                .positiveKeyword("investigation", 10)
                .positiveKeyword("kidnapping", 10)
                .positiveKeyword("escape", 10)
                .positiveKeyword("on the run", 10)
                .positiveKeyword("terrorism", 10)
                .negativeKeyword("cheerful", 14)
                .negativeKeyword("comforting", 14)
                .negativeKeyword("playful", 12)
                .build();
    }

    private TagRule dark() {
        return TagRule.builder(RecommendationTag.DARK)
                .positiveGenre(GenreNames.HORROR, 20)
                .positiveGenre(GenreNames.THRILLER, 18)
                .positiveGenre(GenreNames.CRIME, 12)
                .positiveGenre(GenreNames.MYSTERY, 10)
                .positiveGenre(GenreNames.WAR, 8)
                .positiveGenre(GenreNames.DRAMA, 6)
                .negativeGenre(GenreNames.FAMILY, 10)
                .negativeGenre(GenreNames.ANIMATION, 10)
                .negativeGenre(GenreNames.COMEDY, 8)
                .positiveKeyword("neo-noir", 18)
                .positiveKeyword("serial killer", 14)
                .positiveKeyword("corruption", 12)
                .positiveKeyword("grief", 14)
                .positiveKeyword("tragedy", 14)
                .positiveKeyword("depressing", 16)
                .positiveKeyword("grim", 14)
                .positiveKeyword("bleak", 16)
                .positiveKeyword("tragic", 12)
                .positiveKeyword("melancholic", 12)
                .positiveKeyword("obsession", 10)
                .negativeKeyword("cheerful", 16)
                .negativeKeyword("lighthearted", 16)
                .build();
    }

    private TagRule emotional() {
        return TagRule.builder(RecommendationTag.EMOTIONAL)
                .positiveGenre(GenreNames.DRAMA, 28)
                .positiveGenre(GenreNames.ROMANCE, 12)
                .positiveGenre(GenreNames.MUSIC, 8)
                .positiveGenre(GenreNames.FAMILY, 8)
                .positiveGenre(GenreNames.ANIMATION, 4)
                .negativeGenre(GenreNames.HORROR, 10)
                .negativeGenre(GenreNames.ACTION, 8)
                .positiveKeyword("sentimental", 18)
                .positiveKeyword("loss of loved one", 18)
                .positiveKeyword("grief", 18)
                .positiveKeyword("tearjerker", 18)
                .positiveKeyword("heartfelt", 16)
                .positiveKeyword("heartbreak", 16)
                .positiveKeyword("emotional", 16)
                .positiveKeyword("moving", 14)
                .positiveKeyword("melancholic", 14)
                .positiveKeyword("bittersweet ending", 14)
                .positiveKeyword("bittersweet", 12)
                .positiveKeyword("emotional growth", 14)
                .positiveKeyword("sadness", 12)
                .positiveKeyword("warm tragedy", 14)
                .positiveKeyword("friendship", 12)
                .positiveKeyword("family", 12)
                .positiveKeyword("terminal illness", 16)
                .positiveKeyword("illness", 8)
                .positiveKeyword("mother daughter relationship", 10)
                .positiveKeyword("father son relationship", 10)
                .positiveKeyword("mother son relationship", 10)
                .positiveKeyword("father daughter relationship", 10)
                .positiveKeyword("comforting", 10)
                .negativeKeyword("gore", 16)
                .negativeKeyword("serial killer", 16)
                .negativeKeyword("terrorism", 12)
                .build();
    }

    private TagRule romantic() {
        return TagRule.builder(RecommendationTag.ROMANTIC)
                .requiredGenre(GenreNames.ROMANCE)
                .positiveGenre(GenreNames.ROMANCE, 35)
                .positiveGenre(GenreNames.DRAMA, 10)
                .positiveGenre(GenreNames.COMEDY, 6)
                .positiveGenre(GenreNames.FANTASY, 4)
                .negativeGenre(GenreNames.HORROR, 10)
                .negativeGenre(GenreNames.CRIME, 10)
                .negativeGenre(GenreNames.WAR, 8)
                .positiveKeyword("romance", 18)
                .positiveKeyword("romantic", 16)
                .positiveKeyword("love", 12)
                .positiveKeyword("first love", 22)
                .positiveKeyword("romcom", 14)
                .positiveKeyword("falling in love", 16)
                .positiveKeyword("relationship", 10)
                .positiveKeyword("adoring", 10)
                .positiveKeyword("admiring", 10)
                .negativeKeyword("murder", 16)
                .negativeKeyword("serial killer", 20)
                .negativeKeyword("gore", 20)
                .build();
    }

    private TagRule hopeful() {
        return TagRule.builder(RecommendationTag.HOPEFUL)
                .positiveGenre(GenreNames.DRAMA, 16)
                .positiveGenre(GenreNames.FAMILY, 14)
                .positiveGenre(GenreNames.ANIMATION, 10)
                .positiveGenre(GenreNames.MUSIC, 6)
                .positiveGenre(GenreNames.COMEDY, 4)
                .negativeGenre(GenreNames.HORROR, 12)
                .negativeGenre(GenreNames.CRIME, 10)
                .negativeGenre(GenreNames.THRILLER, 10)
                .positiveKeyword("hopeful", 22)
                .positiveKeyword("inspirational", 18)
                .positiveKeyword("comforting", 14)
                .positiveKeyword("uplifting", 18)
                .positiveKeyword("heartwarming", 18)
                .positiveKeyword("healing", 14)
                .positiveKeyword("second chance", 12)
                .positiveKeyword("joyful", 12)
                .positiveKeyword("cheerful", 10)
                .positiveKeyword("optimistic", 16)
                .positiveKeyword("triumph", 14)
                .positiveKeyword("new beginning", 14)
                .positiveKeyword("perseverance", 12)
                .positiveKeyword("dream", 8)
                .positiveKeyword("friendship", 8)
                .positiveKeyword("found family", 10)
                .positiveKeyword("rescue", 8)
                .negativeKeyword("depressing", 18)
                .negativeKeyword("tragedy", 16)
                .negativeKeyword("grief", 16)
                .negativeKeyword("serial killer", 20)
                .build();
    }

    private TagRule healing() {
        return TagRule.builder(RecommendationTag.HEALING)
                .positiveGenre(GenreNames.DRAMA, 18)
                .positiveGenre(GenreNames.FAMILY, 16)
                .positiveGenre(GenreNames.ROMANCE, 10)
                .positiveGenre(GenreNames.ANIMATION, 10)
                .positiveGenre(GenreNames.COMEDY, 6)
                .hardExcludedGenre(GenreNames.HORROR)
                .positiveKeyword("healing", 24)
                .positiveKeyword("comforting", 18)
                .positiveKeyword("heartwarming", 18)
                .positiveKeyword("friendship", 12)
                .positiveKeyword("found family", 14)
                .positiveKeyword("second chance", 14)
                .positiveKeyword("slice of life", 14)
                .positiveKeyword("small town", 10)
                .positiveKeyword("self discovery", 12)
                .positiveKeyword("family", 10)
                .positiveKeyword("companionship", 10)
                .positiveKeyword("gentle", 12)
                .positiveKeyword("sentimental", 8)
                .positiveKeyword("holiday", 8)
                .negativeKeyword("gore", 18)
                .negativeKeyword("serial killer", 18)
                .negativeKeyword("torture", 18)
                .negativeKeyword("brutality", 16)
                .build();
    }

    private TagRule spectacle() {
        return TagRule.builder(RecommendationTag.SPECTACLE)
                .requiredGenre(GenreNames.ACTION)
                .requiredGenre(GenreNames.ADVENTURE)
                .requiredGenre(GenreNames.FANTASY)
                .requiredGenre(GenreNames.SF)
                .positiveGenre(GenreNames.ACTION, 24)
                .positiveGenre(GenreNames.ADVENTURE, 24)
                .positiveGenre(GenreNames.FANTASY, 14)
                .positiveGenre(GenreNames.SF, 18)
                .positiveGenre(GenreNames.ANIMATION, 2)
                .negativeGenre(GenreNames.FAMILY, 10)
                .negativeGenre(GenreNames.ANIMATION, 4)
                .negativeGenre(GenreNames.DOCUMENTARY, 14)
                .positiveKeyword("superhero", 20)
                .positiveKeyword("wizard", 12)
                .positiveKeyword("magic", 12)
                .positiveKeyword("saving the world", 16)
                .positiveKeyword("alien invasion", 16)
                .positiveKeyword("fantasy world", 10)
                .positiveKeyword("super power", 14)
                .positiveKeyword("battle", 12)
                .positiveKeyword("monster", 8)
                .positiveKeyword("epic battle", 16)
                .positiveKeyword("space battle", 16)
                .positiveKeyword("giant robot", 14)
                .positiveKeyword("post-apocalyptic future", 10)
                .negativeKeyword("small town", 10)
                .negativeKeyword("slice of life", 14)
                .negativeKeyword("anime", 10)
                .negativeKeyword("3d animation", 12)
                .negativeKeyword("talking animal", 14)
                .negativeKeyword("based on children's book", 12)
                .negativeKeyword("based on fairy tale", 10)
                .build();
    }

    private TagRule creepy() {
        return TagRule.builder(RecommendationTag.CREEPY)
                .requiredGenre(GenreNames.HORROR)
                .positiveGenre(GenreNames.HORROR, 30)
                .positiveGenre(GenreNames.MYSTERY, 14)
                .positiveGenre(GenreNames.THRILLER, 12)
                .hardExcludedGenre(GenreNames.FAMILY)
                .hardExcludedGenre(GenreNames.ANIMATION)
                .positiveKeyword("supernatural horror", 22)
                .positiveKeyword("psychological horror", 20)
                .positiveKeyword("ghost", 18)
                .positiveKeyword("exorcism", 20)
                .positiveKeyword("curse", 18)
                .positiveKeyword("demon", 18)
                .positiveKeyword("witch", 14)
                .positiveKeyword("gore", 12)
                .positiveKeyword("body horror", 18)
                .positiveKeyword("supernatural", 10)
                .negativeKeyword("cheerful", 16)
                .negativeKeyword("comforting", 16)
                .build();
    }

    private TagRule withFamily() {
        return TagRule.builder(RecommendationTag.WITH_FAMILY)
                .positiveGenre(GenreNames.FAMILY, 26)
                .positiveGenre(GenreNames.ANIMATION, 20)
                .positiveGenre(GenreNames.COMEDY, 10)
                .positiveGenre(GenreNames.MUSIC, 4)
                .positiveGenre(GenreNames.ADVENTURE, 4)
                .positiveGenre(GenreNames.FANTASY, 4)
                .hardExcludedGenre(GenreNames.HORROR)
                .hardExcludedGenre(GenreNames.THRILLER)
                .hardExcludedGenre(GenreNames.CRIME)
                .hardExcludedKeyword("ghost")
                .hardExcludedKeyword("curse")
                .hardExcludedKeyword("witch")
                .hardExcludedKeyword("demon")
                .hardExcludedKeyword("psychological horror")
                .hardExcludedKeyword("supernatural horror")
                .hardExcludedKeyword("body horror")
                .positiveKeyword("family", 18)
                .positiveKeyword("friendship", 10)
                .positiveKeyword("cheerful", 10)
                .positiveKeyword("comforting", 10)
                .positiveKeyword("playful", 8)
                .positiveKeyword("talking animal", 12)
                .positiveKeyword("christmas", 8)
                .positiveKeyword("joyful", 8)
                .positiveKeyword("lighthearted", 10)
                .positiveKeyword("holiday", 8)
                .positiveKeyword("3d animation", 8)
                .positiveKeyword("based on children's book", 10)
                .positiveKeyword("animals", 6)
                .positiveKeyword("found family", 10)
                .positiveKeyword("children", 8)
                .hardExcludedKeyword("gore")
                .hardExcludedKeyword("serial killer")
                .hardExcludedKeyword("exorcism")
                .hardExcludedKeyword("zombie")
                .negativeKeyword("grief", 14)
                .negativeKeyword("depressing", 16)
                .negativeKeyword("tragedy", 12)
                .negativeKeyword("dark comedy", 12)
                .build();
    }

    private TagRule withPartner() {
        return TagRule.builder(RecommendationTag.WITH_PARTNER)
                .positiveGenre(GenreNames.ROMANCE, 32)
                .positiveGenre(GenreNames.DRAMA, 8)
                .positiveGenre(GenreNames.COMEDY, 6)
                .hardExcludedGenre(GenreNames.HORROR)
                .hardExcludedGenre(GenreNames.WAR)
                .hardExcludedGenre(GenreNames.CRIME)
                .positiveKeyword("romance", 16)
                .positiveKeyword("romantic", 14)
                .positiveKeyword("first love", 16)
                .positiveKeyword("love", 10)
                .positiveKeyword("romcom", 12)
                .positiveKeyword("falling in love", 14)
                .positiveKeyword("relationship", 10)
                .positiveKeyword("intimate", 8)
                .positiveKeyword("friends in love", 14)
                .positiveKeyword("date", 8)
                .positiveKeyword("christmas", 6)
                .hardExcludedKeyword("gore")
                .hardExcludedKeyword("serial killer")
                .hardExcludedKeyword("exorcism")
                .hardExcludedKeyword("zombie")
                .build();
    }

    private TagRule lateNight() {
        return TagRule.builder(RecommendationTag.LATE_NIGHT)
                .requiredGenre(GenreNames.HORROR)
                .requiredGenre(GenreNames.THRILLER)
                .requiredGenre(GenreNames.MYSTERY)
                .requiredGenre(GenreNames.CRIME)
                .positiveGenre(GenreNames.HORROR, 20)
                .positiveGenre(GenreNames.THRILLER, 18)
                .positiveGenre(GenreNames.MYSTERY, 12)
                .positiveGenre(GenreNames.CRIME, 8)
                .hardExcludedGenre(GenreNames.FAMILY)
                .hardExcludedGenre(GenreNames.ANIMATION)
                .positiveKeyword("suspenseful", 14)
                .positiveKeyword("supernatural horror", 18)
                .positiveKeyword("psychological horror", 16)
                .positiveKeyword("serial killer", 12)
                .positiveKeyword("ghost", 12)
                .positiveKeyword("investigation", 8)
                .negativeKeyword("comforting", 14)
                .negativeKeyword("cheerful", 14)
                .build();
    }

    private TagRule violent() {
        return TagRule.builder(RecommendationTag.VIOLENT)
                .positiveGenre(GenreNames.ACTION, 16)
                .positiveGenre(GenreNames.CRIME, 12)
                .positiveGenre(GenreNames.WAR, 10)
                .positiveGenre(GenreNames.HORROR, 10)
                .positiveGenre(GenreNames.THRILLER, 8)
                .negativeGenre(GenreNames.FAMILY, 12)
                .negativeGenre(GenreNames.ANIMATION, 10)
                .positiveKeyword("gore", 25)
                .positiveKeyword("violence", 18)
                .positiveKeyword("battle", 12)
                .positiveKeyword("serial killer", 12)
                .positiveKeyword("murder", 10)
                .positiveKeyword("assassin", 10)
                .positiveKeyword("terrorism", 10)
                .positiveKeyword("fight", 8)
                .positiveKeyword("blood", 12)
                .positiveKeyword("brutal", 14)
                .positiveKeyword("brutality", 14)
                .positiveKeyword("gunfight", 12)
                .positiveKeyword("slasher horror", 14)
                .build();
    }

    private TagRule sad() {
        return TagRule.builder(RecommendationTag.SAD)
                .positiveGenre(GenreNames.DRAMA, 20)
                .positiveGenre(GenreNames.ROMANCE, 8)
                .positiveGenre(GenreNames.WAR, 8)
                .positiveGenre(GenreNames.MUSIC, 6)
                .negativeGenre(GenreNames.COMEDY, 12)
                .positiveKeyword("loss of loved one", 20)
                .positiveKeyword("grief", 20)
                .positiveKeyword("tragedy", 18)
                .positiveKeyword("depressing", 18)
                .positiveKeyword("dying and death", 16)
                .positiveKeyword("death", 14)
                .positiveKeyword("melancholic", 16)
                .positiveKeyword("sadness", 16)
                .positiveKeyword("bittersweet ending", 14)
                .positiveKeyword("warm tragedy", 14)
                .positiveKeyword("tears guaranteed", 18)
                .positiveKeyword("orphan", 10)
                .negativeKeyword("cheerful", 20)
                .negativeKeyword("hilarious", 20)
                .negativeKeyword("lighthearted", 16)
                .build();
    }

    private TagRule slowBurn() {
        return TagRule.builder(RecommendationTag.SLOW_BURN)
                .positiveGenre(GenreNames.DRAMA, 14)
                .positiveGenre(GenreNames.MYSTERY, 8)
                .positiveGenre(GenreNames.HISTORY, 4)
                .negativeGenre(GenreNames.ACTION, 12)
                .negativeGenre(GenreNames.COMEDY, 10)
                .negativeGenre(GenreNames.ANIMATION, 10)
                .runtimeWeight(150, 25)
                .runtimeWeight(130, 15)
                .runtimeWeight(120, 10)
                .positiveKeyword("reflective", 18)
                .positiveKeyword("thoughtful", 16)
                .positiveKeyword("philosophical", 16)
                .positiveKeyword("social commentary", 12)
                .positiveKeyword("slice of life", 18)
                .positiveKeyword("nostalgic", 10)
                .positiveKeyword("small town", 8)
                .negativeKeyword("battle", 12)
                .negativeKeyword("superhero", 12)
                .negativeKeyword("rescue", 10)
                .negativeKeyword("hilarious", 10)
                .build();
    }

    private TagRule longRunning() {
        return TagRule.builder(RecommendationTag.LONG_RUNNING)
                .runtimeWeight(160, 100)
                .build();
    }

    private TagRule investigation() {
        return TagRule.builder(RecommendationTag.INVESTIGATION)
                .requiredGenre(GenreNames.MYSTERY)
                .requiredGenre(GenreNames.CRIME)
                .requiredKeyword("detective")
                .requiredKeyword("investigation")
                .requiredKeyword("police")
                .requiredKeyword("murder mystery")
                .requiredKeyword("whodunit")
                .requiredKeyword("crime investigation")
                .requiredKeyword("homicide investigation")
                .requiredKeyword("police detective")
                .requiredKeyword("female investigator")
                .positiveGenre(GenreNames.MYSTERY, 28)
                .positiveGenre(GenreNames.CRIME, 24)
                .positiveGenre(GenreNames.THRILLER, 10)
                .hardExcludedGenre(GenreNames.ANIMATION)
                .hardExcludedGenre(GenreNames.FAMILY)
                .positiveKeyword("detective", 22)
                .positiveKeyword("investigation", 22)
                .positiveKeyword("police", 18)
                .positiveKeyword("murder mystery", 18)
                .positiveKeyword("whodunit", 18)
                .positiveKeyword("private investigator", 16)
                .positiveKeyword("crime investigation", 16)
                .positiveKeyword("homicide investigation", 16)
                .positiveKeyword("police detective", 16)
                .positiveKeyword("female investigator", 12)
                .positiveKeyword("missing person", 10)
                .positiveKeyword("series of murders", 10)
                .positiveKeyword("kidnapping", 10)
                .positiveKeyword("murder", 8)
                .positiveKeyword("serial killer", 8)
                .positiveKeyword("conspiracy", 8)
                .positiveKeyword("mystery", 8)
                .negativeKeyword("supernatural horror", 16)
                .negativeKeyword("ghost", 16)
                .negativeKeyword("demon", 16)
                .negativeKeyword("zombie", 20)
                .build();
    }

    private TagRule mystery() {
        return TagRule.builder(RecommendationTag.MYSTERY)
                .requiredGenre(GenreNames.MYSTERY)
                .requiredGenre(GenreNames.THRILLER)
                .requiredKeyword("mystery")
                .requiredKeyword("mysterious")
                .requiredKeyword("disappearance")
                .requiredKeyword("missing person")
                .requiredKeyword("secret")
                .requiredKeyword("hidden truth")
                .requiredKeyword("whodunit")
                .positiveGenre(GenreNames.MYSTERY, 26)
                .positiveGenre(GenreNames.THRILLER, 14)
                .positiveGenre(GenreNames.DRAMA, 8)
                .positiveGenre(GenreNames.CRIME, 8)
                .positiveGenre(GenreNames.FANTASY, 4)
                .positiveGenre(GenreNames.HORROR, 4)
                .positiveKeyword("mystery", 20)
                .positiveKeyword("mysterious", 14)
                .positiveKeyword("disappearance", 18)
                .positiveKeyword("missing person", 18)
                .positiveKeyword("secret", 12)
                .positiveKeyword("hidden truth", 16)
                .positiveKeyword("whodunit", 18)
                .positiveKeyword("murder mystery", 14)
                .positiveKeyword("conspiracy", 12)
                .positiveKeyword("puzzle", 12)
                .positiveKeyword("parallel world", 6)
                .negativeKeyword("talking animal", 14)
                .negativeKeyword("slapstick", 12)
                .build();
    }

    private TagRule zombie() {
        return TagRule.builder(RecommendationTag.ZOMBIE)
                .requiredGenre(GenreNames.HORROR)
                .requiredGenre(GenreNames.THRILLER)
                .requiredGenre(GenreNames.SF)
                .requiredGenre(GenreNames.ACTION)
                .requiredKeyword("zombie")
                .requiredKeyword("zombie apocalypse")
                .requiredKeyword("undead")
                .requiredKeyword("infected")
                .positiveGenre(GenreNames.HORROR, 20)
                .positiveGenre(GenreNames.THRILLER, 8)
                .positiveGenre(GenreNames.SF, 8)
                .positiveGenre(GenreNames.ACTION, 8)
                .hardExcludedGenre(GenreNames.FAMILY)
                .hardExcludedGenre(GenreNames.ANIMATION)
                .positiveKeyword("zombie", 30)
                .positiveKeyword("zombie apocalypse", 35)
                .positiveKeyword("undead", 30)
                .positiveKeyword("infected", 25)
                .positiveKeyword("survival horror", 15)
                .positiveKeyword("post-apocalyptic future", 10)
                .positiveKeyword("outbreak", 10)
                .hardExcludedKeyword("talking animal")
                .build();
    }

    private TagRule disaster() {
        return TagRule.builder(RecommendationTag.DISASTER)
                .requiredGenre(GenreNames.ACTION)
                .requiredGenre(GenreNames.THRILLER)
                .requiredGenre(GenreNames.SF)
                .requiredGenre(GenreNames.DRAMA)
                .requiredKeyword("disaster")
                .requiredKeyword("rescue")
                .requiredKeyword("end of the world")
                .requiredKeyword("alien invasion")
                .requiredKeyword("outbreak")
                .requiredKeyword("pandemic")
                .positiveGenre(GenreNames.ACTION, 14)
                .positiveGenre(GenreNames.THRILLER, 14)
                .positiveGenre(GenreNames.SF, 10)
                .positiveGenre(GenreNames.DRAMA, 8)
                .positiveGenre(GenreNames.ADVENTURE, 8)
                .hardExcludedGenre(GenreNames.FAMILY)
                .positiveKeyword("disaster", 24)
                .positiveKeyword("rescue", 16)
                .positiveKeyword("end of the world", 20)
                .positiveKeyword("alien invasion", 18)
                .positiveKeyword("outbreak", 18)
                .positiveKeyword("pandemic", 18)
                .positiveKeyword("natural disaster", 18)
                .positiveKeyword("earthquake", 18)
                .positiveKeyword("volcanic eruption", 18)
                .positiveKeyword("volcano", 16)
                .positiveKeyword("asteroid", 18)
                .positiveKeyword("comet", 18)
                .positiveKeyword("nuclear catastrophe", 18)
                .positiveKeyword("catastrophe", 18)
                .positiveKeyword("global threat", 14)
                .positiveKeyword("environmental disaster", 16)
                .positiveKeyword("storm", 12)
                .positiveKeyword("flood", 12)
                .positiveKeyword("evacuation", 12)
                .positiveKeyword("apocalypse", 16)
                .positiveKeyword("post-apocalyptic future", 10)
                .positiveKeyword("survival", 10)
                .negativeKeyword("cheerful", 10)
                .negativeKeyword("talking animal", 20)
                .build();
    }

    private TagRule trueStory() {
        return TagRule.builder(RecommendationTag.TRUE_STORY)
                .requiredKeyword("based on true story")
                .requiredKeyword("biography")
                .positiveGenre(GenreNames.DRAMA, 10)
                .positiveGenre(GenreNames.WAR, 6)
                .positiveGenre(GenreNames.HISTORY, 6)
                .positiveGenre(GenreNames.PERIOD, 6)
                .positiveKeyword("based on true story", 35)
                .positiveKeyword("biography", 25)
                .positiveKeyword("historical fiction", 10)
                .negativeKeyword("fantasy world", 20)
                .negativeKeyword("zombie", 20)
                .negativeKeyword("superhero", 18)
                .negativeKeyword("magic", 16)
                .build();
    }

    private TagRule comingOfAge() {
        return TagRule.builder(RecommendationTag.COMING_OF_AGE)
                .requiredGenre(GenreNames.DRAMA)
                .requiredGenre(GenreNames.ROMANCE)
                .requiredGenre(GenreNames.COMEDY)
                .requiredKeyword("coming of age")
                .requiredKeyword("high school")
                .requiredKeyword("school")
                .requiredKeyword("teenage girl")
                .requiredKeyword("teenage boy")
                .requiredKeyword("teenager")
                .requiredKeyword("youth")
                .requiredKeyword("adolescence")
                .positiveGenre(GenreNames.DRAMA, 18)
                .positiveGenre(GenreNames.ROMANCE, 8)
                .positiveGenre(GenreNames.COMEDY, 6)
                .positiveGenre(GenreNames.FAMILY, 6)
                .positiveGenre(GenreNames.ANIMATION, 4)
                .positiveKeyword("coming of age", 30)
                .positiveKeyword("high school", 16)
                .positiveKeyword("school", 10)
                .positiveKeyword("teenage girl", 10)
                .positiveKeyword("teenage boy", 10)
                .positiveKeyword("teenager", 12)
                .positiveKeyword("youth", 12)
                .positiveKeyword("adolescence", 12)
                .positiveKeyword("childhood", 10)
                .positiveKeyword("childhood friends", 12)
                .positiveKeyword("elementary school", 10)
                .positiveKeyword("kids", 8)
                .positiveKeyword("self discovery", 12)
                .positiveKeyword("youth melodrama", 12)
                .positiveKeyword("bullying", 8)
                .positiveKeyword("friendship", 8)
                .positiveKeyword("first love", 8)
                .positiveKeyword("slice of life", 6)
                .negativeKeyword("serial killer", 20)
                .negativeKeyword("gore", 20)
                .negativeKeyword("exorcism", 20)
                .negativeKeyword("war", 12)
                .build();
    }

    private TagRule friendship() {
        return TagRule.builder(RecommendationTag.FRIENDSHIP)
                .requiredKeyword("friendship")
                .requiredKeyword("best friend")
                .requiredKeyword("childhood friends")
                .requiredKeyword("found family")
                .requiredKeyword("teamwork")
                .requiredKeyword("group of friends")
                .positiveGenre(GenreNames.DRAMA, 14)
                .positiveGenre(GenreNames.COMEDY, 10)
                .positiveGenre(GenreNames.FAMILY, 12)
                .positiveGenre(GenreNames.ANIMATION, 12)
                .positiveGenre(GenreNames.ADVENTURE, 8)
                .positiveGenre(GenreNames.ROMANCE, 4)
                .positiveKeyword("friendship", 28)
                .positiveKeyword("best friend", 16)
                .positiveKeyword("childhood friends", 16)
                .positiveKeyword("found family", 18)
                .positiveKeyword("teamwork", 14)
                .positiveKeyword("companionship", 12)
                .positiveKeyword("group of friends", 14)
                .positiveKeyword("buddy comedy", 10)
                .negativeKeyword("serial killer", 14)
                .negativeKeyword("gore", 16)
                .negativeKeyword("exorcism", 16)
                .build();
    }

    private TagRule survival() {
        return TagRule.builder(RecommendationTag.SURVIVAL)
                .requiredGenre(GenreNames.THRILLER)
                .requiredGenre(GenreNames.ACTION)
                .requiredGenre(GenreNames.ADVENTURE)
                .requiredGenre(GenreNames.HORROR)
                .requiredGenre(GenreNames.SF)
                .requiredKeyword("survival")
                .requiredKeyword("stranded")
                .requiredKeyword("survival horror")
                .requiredKeyword("post-apocalyptic future")
                .requiredKeyword("outbreak")
                .requiredKeyword("pandemic")
                .requiredKeyword("wilderness")
                .requiredKeyword("shipwreck")
                .requiredKeyword("apocalypse")
                .requiredKeyword("trapped")
                .positiveGenre(GenreNames.THRILLER, 16)
                .positiveGenre(GenreNames.ACTION, 12)
                .positiveGenre(GenreNames.ADVENTURE, 12)
                .positiveGenre(GenreNames.HORROR, 10)
                .positiveGenre(GenreNames.SF, 10)
                .positiveGenre(GenreNames.DRAMA, 8)
                .positiveKeyword("survival", 24)
                .positiveKeyword("survival horror", 18)
                .positiveKeyword("stranded", 18)
                .positiveKeyword("post-apocalyptic future", 18)
                .positiveKeyword("outbreak", 16)
                .positiveKeyword("pandemic", 16)
                .positiveKeyword("wilderness", 16)
                .positiveKeyword("shipwreck", 16)
                .positiveKeyword("apocalypse", 14)
                .positiveKeyword("trapped", 12)
                .positiveKeyword("alone", 10)
                .positiveKeyword("rescue", 10)
                .positiveKeyword("virus", 10)
                .positiveKeyword("infected", 10)
                .negativeKeyword("cheerful", 16)
                .negativeKeyword("lighthearted", 16)
                .negativeKeyword("talking animal", 18)
                .build();
    }

    private TagRule revenge() {
        return TagRule.builder(RecommendationTag.REVENGE)
                .requiredGenre(GenreNames.ACTION)
                .requiredGenre(GenreNames.THRILLER)
                .requiredGenre(GenreNames.CRIME)
                .requiredGenre(GenreNames.DRAMA)
                .requiredKeyword("revenge")
                .requiredKeyword("vengeance")
                .requiredKeyword("vendetta")
                .requiredKeyword("retaliation")
                .requiredKeyword("retribution")
                .requiredKeyword("vigilante")
                .positiveGenre(GenreNames.ACTION, 16)
                .positiveGenre(GenreNames.THRILLER, 14)
                .positiveGenre(GenreNames.CRIME, 14)
                .positiveGenre(GenreNames.DRAMA, 8)
                .positiveGenre(GenreNames.WAR, 4)
                .positiveKeyword("revenge", 28)
                .positiveKeyword("vengeance", 24)
                .positiveKeyword("vendetta", 24)
                .positiveKeyword("retaliation", 18)
                .positiveKeyword("retribution", 18)
                .positiveKeyword("vigilante", 14)
                .positiveKeyword("justice", 8)
                .positiveKeyword("assassin", 10)
                .positiveKeyword("rape and revenge", 20)
                .positiveKeyword("murder", 6)
                .negativeKeyword("cheerful", 16)
                .negativeKeyword("lighthearted", 16)
                .negativeKeyword("talking animal", 18)
                .build();
    }
}
